<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class AddressLevelInfo extends Model
{
    const ADDRESS_LEVEL_INFO_ID = 'address_level_info_id';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const ADD_INFO = 'add_info';
    const LEVEL = 'level';
    const PARENT_ID = 'parent_id';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'address_level_info',
                'address_level_info_id',
                [
                    'address_level_info_id' => ['name' => _META_('mp.address_level_info.address_level_info_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.address_level_info.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.address_level_info.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'add_info' => ['name' => _META_('mp.address_level_info.add_info'), 'type' => 'text', 'length' => 128, 'required' => true],
                    'level' => ['name' => _META_('mp.address_level_info.level'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'parent_id' => ['name' => _META_('mp.address_level_info.parent_id'), 'type' => 'int', 'length' => 10, 'db_insert' => true, 'required' => true],
                ],
                [
                    'auto_increment_id' => 'address_level_info_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getAddressLevelInfoID()
    {
        return $this->__get(self::ADDRESS_LEVEL_INFO_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return AddressLevelInfo
     */
    public function setAddressLevelInfoID($value)
    {
        $this->__set(self::ADDRESS_LEVEL_INFO_ID, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return AddressLevelInfo
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return AddressLevelInfo
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 地址信息
     * @return string
     */
    public function getAddInfo()
    {
        return $this->__get(self::ADD_INFO);
    }

    /**
     * Sets 地址信息
     * @param string $value
     * @return AddressLevelInfo
     */
    public function setAddInfo($value)
    {
        $this->__set(self::ADD_INFO, $value);

        return $this;
    }

    /**
     * Gets 级别
     * @return int
     */
    public function getLevel()
    {
        return $this->__get(self::LEVEL);
    }

    /**
     * Sets 级别
     * @param int $value
     * @return AddressLevelInfo
     */
    public function setLevel($value)
    {
        $this->__set(self::LEVEL, $value);

        return $this;
    }

    /**
     * Gets 上一级地址信息id
     * @return int
     */
    public function getParentID()
    {
        return $this->__get(self::PARENT_ID);
    }

    /**
     * Sets 上一级地址信息id
     * @param int $value
     * @return AddressLevelInfo
     */
    public function setParentID($value)
    {
        $this->__set(self::PARENT_ID, $value);

        return $this;
    }
}
?>