<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class Album extends Model
{
    const ALBUM_ID = 'album_id';
    const _CREATED_AT = '_created_at';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const CAROUSEL_ID = 'carousel_id';
    const TITLE = 'title';
    const COVER_IMG = 'cover_img';
    const SORT_NO = 'sort_no';
    const COMMENT = 'comment';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'album',
                'album_id',
                [
                    'album_id' => ['name' => _META_('mp.album.album_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('mp.album._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.album.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.album.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'carousel_id' => ['name' => _META_('mp.album.carousel_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'title' => ['name' => _META_('mp.album.title'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'cover_img' => ['name' => _META_('mp.album.cover_img'), 'type' => 'url', 'required' => true],
                    'sort_no' => ['name' => _META_('mp.album.sort_no'), 'type' => 'float', 'db_insert' => true, 'required' => true],
                    'comment' => ['name' => _META_('mp.album.comment'), 'type' => 'text'],
                ],
                [
                    'auto_increment_id' => 'album_id',
                    'create_timestamp' => '_created_at',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getAlbumID()
    {
        return $this->__get(self::ALBUM_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return Album
     */
    public function setAlbumID($value)
    {
        $this->__set(self::ALBUM_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return Album
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets 公众账号id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets 公众账号id
     * @param int $value
     * @return Album
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return Album
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 轮播id carousel.carousel_id
     * @return int
     */
    public function getCarouselID()
    {
        return $this->__get(self::CAROUSEL_ID);
    }

    /**
     * Sets 轮播id carousel.carousel_id
     * @param int $value
     * @return Album
     */
    public function setCarouselID($value)
    {
        $this->__set(self::CAROUSEL_ID, $value);

        return $this;
    }

    /**
     * Gets 相册名称
     * @return string
     */
    public function getTitle()
    {
        return $this->__get(self::TITLE);
    }

    /**
     * Sets 相册名称
     * @param string $value
     * @return Album
     */
    public function setTitle($value)
    {
        $this->__set(self::TITLE, $value);

        return $this;
    }

    /**
     * Gets 封面图片地址
     * @return string
     */
    public function getCoverImg()
    {
        return $this->__get(self::COVER_IMG);
    }

    /**
     * Sets 封面图片地址
     * @param string $value
     * @return Album
     */
    public function setCoverImg($value)
    {
        $this->__set(self::COVER_IMG, $value);

        return $this;
    }

    /**
     * Gets 排序
     * @return float
     */
    public function getSortNo()
    {
        return $this->__get(self::SORT_NO);
    }

    /**
     * Sets 排序
     * @param float $value
     * @return Album
     */
    public function setSortNo($value)
    {
        $this->__set(self::SORT_NO, $value);

        return $this;
    }

    /**
     * Gets 备注
     * @return string
     */
    public function getComment()
    {
        return $this->__get(self::COMMENT);
    }

    /**
     * Sets 备注
     * @param string $value
     * @return Album
     */
    public function setComment($value)
    {
        $this->__set(self::COMMENT, $value);

        return $this;
    }
}
?>