<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class Area extends Model
{
    const AREA_ID = 'area_id';
    const NAME = 'name';
    const CITY_ID = 'city_id';
    const CREATED = 'created';
    const UPDATED = 'updated';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'area',
                'area_id',
                [
                    'area_id' => ['name' => _META_('mp.area.area_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'name' => ['name' => _META_('mp.area.name'), 'type' => 'text', 'length' => 128, 'required' => true],
                    'city_id' => ['name' => _META_('mp.area.city_id'), 'type' => 'int', 'length' => 11, 'required' => true],
                    'created' => ['name' => _META_('mp.area.created'), 'type' => 'int', 'length' => 11],
                    'updated' => ['name' => _META_('mp.area.updated'), 'type' => 'int', 'length' => 11],
                ],
                [
                    'auto_increment_id' => 'area_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getAreaID()
    {
        return $this->__get(self::AREA_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return Area
     */
    public function setAreaID($value)
    {
        $this->__set(self::AREA_ID, $value);

        return $this;
    }

    /**
     * Gets 城区名称
     * @return string
     */
    public function getName()
    {
        return $this->__get(self::NAME);
    }

    /**
     * Sets 城区名称
     * @param string $value
     * @return Area
     */
    public function setName($value)
    {
        $this->__set(self::NAME, $value);

        return $this;
    }

    /**
     * Gets 所属城市编号
     * @return int
     */
    public function getCityID()
    {
        return $this->__get(self::CITY_ID);
    }

    /**
     * Sets 所属城市编号
     * @param int $value
     * @return Area
     */
    public function setCityID($value)
    {
        $this->__set(self::CITY_ID, $value);

        return $this;
    }

    /**
     * Gets 
     * @return int
     */
    public function getCreated()
    {
        return $this->__get(self::CREATED);
    }

    /**
     * Sets 
     * @param int $value
     * @return Area
     */
    public function setCreated($value)
    {
        $this->__set(self::CREATED, $value);

        return $this;
    }

    /**
     * Gets 
     * @return int
     */
    public function getUpdated()
    {
        return $this->__get(self::UPDATED);
    }

    /**
     * Sets 
     * @param int $value
     * @return Area
     */
    public function setUpdated($value)
    {
        $this->__set(self::UPDATED, $value);

        return $this;
    }
}
?>