<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class ArticleTagLog extends Model
{
    const ARTICLE_TAG_LOG_ID = 'article_tag_log_id';
    const _CREATED_AT = '_created_at';
    const TAG = 'tag';
    const WX_USER_ID = 'wx_user_id';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'article_tag_log',
                'article_tag_log_id',
                [
                    'article_tag_log_id' => ['name' => _META_('mp.article_tag_log.article_tag_log_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('mp.article_tag_log._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'tag' => ['name' => _META_('mp.article_tag_log.tag'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'wx_user_id' => ['name' => _META_('mp.article_tag_log.wx_user_id'), 'type' => 'text', 'length' => 64],
                ],
                [
                    'auto_increment_id' => 'article_tag_log_id',
                    'create_timestamp' => '_created_at',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getArticleTagLogID()
    {
        return $this->__get(self::ARTICLE_TAG_LOG_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return ArticleTagLog
     */
    public function setArticleTagLogID($value)
    {
        $this->__set(self::ARTICLE_TAG_LOG_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return ArticleTagLog
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets 标签
     * @return string
     */
    public function getTag()
    {
        return $this->__get(self::TAG);
    }

    /**
     * Sets 标签
     * @param string $value
     * @return ArticleTagLog
     */
    public function setTag($value)
    {
        $this->__set(self::TAG, $value);

        return $this;
    }

    /**
     * Gets 用户微信open_id
     * @return string
     */
    public function getWxUserID()
    {
        return $this->__get(self::WX_USER_ID);
    }

    /**
     * Sets 用户微信open_id
     * @param string $value
     * @return ArticleTagLog
     */
    public function setWxUserID($value)
    {
        $this->__set(self::WX_USER_ID, $value);

        return $this;
    }
}
?>