<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class BeaconSetting extends Model
{
    const BEACON_SETTING_ID = 'beacon_setting_id';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const UUID = 'uuid';
    const DESCRIPTION = 'description';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'beacon_setting',
                'beacon_setting_id',
                [
                    'beacon_setting_id' => ['name' => _META_('mp.beacon_setting.beacon_setting_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.beacon_setting.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.beacon_setting.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'uuid' => ['name' => _META_('mp.beacon_setting.uuid'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'description' => ['name' => _META_('mp.beacon_setting.description'), 'type' => 'text', 'length' => 255],
                ],
                [
                    'auto_increment_id' => 'beacon_setting_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getBeaconSettingID()
    {
        return $this->__get(self::BEACON_SETTING_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return BeaconSetting
     */
    public function setBeaconSettingID($value)
    {
        $this->__set(self::BEACON_SETTING_ID, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return BeaconSetting
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return BeaconSetting
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 硬件设备id
     * @return string
     */
    public function getUUID()
    {
        return $this->__get(self::UUID);
    }

    /**
     * Sets 硬件设备id
     * @param string $value
     * @return BeaconSetting
     */
    public function setUUID($value)
    {
        $this->__set(self::UUID, $value);

        return $this;
    }

    /**
     * Gets 设备描述
     * @return string
     */
    public function getDescription()
    {
        return $this->__get(self::DESCRIPTION);
    }

    /**
     * Sets 设备描述
     * @param string $value
     * @return BeaconSetting
     */
    public function setDescription($value)
    {
        $this->__set(self::DESCRIPTION, $value);

        return $this;
    }
}
?>