<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class City extends Model
{
    const CITY_ID = 'city_id';
    const NAME = 'name';
    const PROVINCE_ID = 'province_id';
    const ZIP = 'zip';
    const CREATED = 'created';
    const UPDATED = 'updated';
    const SORT = 'sort';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'city',
                'city_id',
                [
                    'city_id' => ['name' => _META_('mp.city.city_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'name' => ['name' => _META_('mp.city.name'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'province_id' => ['name' => _META_('mp.city.province_id'), 'type' => 'int', 'length' => 11],
                    'zip' => ['name' => _META_('mp.city.zip'), 'type' => 'text', 'length' => 6],
                    'created' => ['name' => _META_('mp.city.created'), 'type' => 'int', 'length' => 11],
                    'updated' => ['name' => _META_('mp.city.updated'), 'type' => 'int', 'length' => 11],
                    'sort' => ['name' => _META_('mp.city.sort'), 'type' => 'int', 'length' => 11, 'db_insert' => true],
                ],
                [
                    'auto_increment_id' => 'city_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getCityID()
    {
        return $this->__get(self::CITY_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return City
     */
    public function setCityID($value)
    {
        $this->__set(self::CITY_ID, $value);

        return $this;
    }

    /**
     * Gets 城市名称
     * @return string
     */
    public function getName()
    {
        return $this->__get(self::NAME);
    }

    /**
     * Sets 城市名称
     * @param string $value
     * @return City
     */
    public function setName($value)
    {
        $this->__set(self::NAME, $value);

        return $this;
    }

    /**
     * Gets 所属省份编号
     * @return int
     */
    public function getProvinceID()
    {
        return $this->__get(self::PROVINCE_ID);
    }

    /**
     * Sets 所属省份编号
     * @param int $value
     * @return City
     */
    public function setProvinceID($value)
    {
        $this->__set(self::PROVINCE_ID, $value);

        return $this;
    }

    /**
     * Gets 邮编(预留)
     * @return string
     */
    public function getZip()
    {
        return $this->__get(self::ZIP);
    }

    /**
     * Sets 邮编(预留)
     * @param string $value
     * @return City
     */
    public function setZip($value)
    {
        $this->__set(self::ZIP, $value);

        return $this;
    }

    /**
     * Gets 
     * @return int
     */
    public function getCreated()
    {
        return $this->__get(self::CREATED);
    }

    /**
     * Sets 
     * @param int $value
     * @return City
     */
    public function setCreated($value)
    {
        $this->__set(self::CREATED, $value);

        return $this;
    }

    /**
     * Gets 
     * @return int
     */
    public function getUpdated()
    {
        return $this->__get(self::UPDATED);
    }

    /**
     * Sets 
     * @param int $value
     * @return City
     */
    public function setUpdated($value)
    {
        $this->__set(self::UPDATED, $value);

        return $this;
    }

    /**
     * Gets 排序,从大到小,大于0表示是热门城市
     * @return int
     */
    public function getSort()
    {
        return $this->__get(self::SORT);
    }

    /**
     * Sets 排序,从大到小,大于0表示是热门城市
     * @param int $value
     * @return City
     */
    public function setSort($value)
    {
        $this->__set(self::SORT, $value);

        return $this;
    }
}
?>