<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class CommunityPhoneBook extends Model
{
    const COMMUNITY_PHONE_BOOK_ID = 'community_phone_book_id';
    const COMMUNITY_ID = 'community_id';
    const MP_USER_ID = 'mp_user_id';
    const NAME = 'name';
    const PHONE = 'phone';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'community_phone_book',
                'community_phone_book_id',
                [
                    'community_phone_book_id' => ['name' => _META_('mp.community_phone_book.community_phone_book_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'community_id' => ['name' => _META_('mp.community_phone_book.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'mp_user_id' => ['name' => _META_('mp.community_phone_book.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'name' => ['name' => _META_('mp.community_phone_book.name'), 'type' => 'text', 'length' => 128, 'required' => true],
                    'phone' => ['name' => _META_('mp.community_phone_book.phone'), 'type' => 'text', 'length' => 32, 'required' => true],
                ],
                [
                    'auto_increment_id' => 'community_phone_book_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getCommunityPhoneBookID()
    {
        return $this->__get(self::COMMUNITY_PHONE_BOOK_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return CommunityPhoneBook
     */
    public function setCommunityPhoneBookID($value)
    {
        $this->__set(self::COMMUNITY_PHONE_BOOK_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return CommunityPhoneBook
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return CommunityPhoneBook
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets 名称
     * @return string
     */
    public function getName()
    {
        return $this->__get(self::NAME);
    }

    /**
     * Sets 名称
     * @param string $value
     * @return CommunityPhoneBook
     */
    public function setName($value)
    {
        $this->__set(self::NAME, $value);

        return $this;
    }

    /**
     * Gets 电话
     * @return string
     */
    public function getPhone()
    {
        return $this->__get(self::PHONE);
    }

    /**
     * Sets 电话
     * @param string $value
     * @return CommunityPhoneBook
     */
    public function setPhone($value)
    {
        $this->__set(self::PHONE, $value);

        return $this;
    }
}
?>