<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class Community extends Model
{
    const COMMUNITY_ID = 'community_id';
    const _CREATED_AT = '_created_at';
    const _UPDATED_AT = '_updated_at';
    const MP_USER_ID = 'mp_user_id';
    const NAME = 'name';
    const PHONE = 'phone';
    const ADMIN_EMAIL = 'admin_email';
    const ADMIN_CC_EMAIL = 'admin_cc_email';
    const COMMENT = 'comment';
    const IS_VIRTUAL = 'is_virtual';
    const IS_APP = 'is_app';
    const VALID = 'valid';
    const BILL_COMMENT = 'bill_comment';
    const BILL_NAME = 'bill_name';
    const ADDRESS = 'address';
    const PROVINCE = 'province';
    const CITY = 'city';
    const AREA = 'area';
    const LONGITUDE = 'longitude';
    const LATITUDE = 'latitude';
    const COMMUNITY_TYPE = 'community_type';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'community',
                'community_id',
                [
                    'community_id' => ['name' => _META_('mp.community.community_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('mp.community._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    '_updated_at' => ['name' => _META_('mp.community._updated_at'), 'type' => 'timestamp', 'required' => true, 'db_insert' => true, 'roc' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.community.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'name' => ['name' => _META_('mp.community.name'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'phone' => ['name' => _META_('mp.community.phone'), 'type' => 'text', 'length' => 128],
                    'admin_email' => ['name' => _META_('mp.community.admin_email'), 'type' => 'text'],
                    'admin_cc_email' => ['name' => _META_('mp.community.admin_cc_email'), 'type' => 'text'],
                    'comment' => ['name' => _META_('mp.community.comment'), 'type' => 'text', 'length' => 128],
                    'is_virtual' => ['name' => _META_('mp.community.is_virtual'), 'type' => 'bool', 'db_insert' => true, 'required' => true],
                    'is_app' => ['name' => _META_('mp.community.is_app'), 'type' => 'bool', 'db_insert' => true, 'required' => true],
                    'valid' => ['name' => _META_('mp.community.valid'), 'type' => 'bool', 'db_insert' => true, 'required' => true],
                    'bill_comment' => ['name' => _META_('mp.community.bill_comment'), 'type' => 'text'],
                    'bill_name' => ['name' => _META_('mp.community.bill_name'), 'type' => 'text', 'length' => 128],
                    'address' => ['name' => _META_('mp.community.address'), 'type' => 'text', 'length' => 128],
                    'province' => ['name' => _META_('mp.community.province'), 'type' => 'text', 'length' => 128],
                    'city' => ['name' => _META_('mp.community.city'), 'type' => 'text', 'length' => 128],
                    'area' => ['name' => _META_('mp.community.area'), 'type' => 'text', 'length' => 128],
                    'longitude' => ['name' => _META_('mp.community.longitude'), 'type' => 'text', 'length' => 64],
                    'latitude' => ['name' => _META_('mp.community.latitude'), 'type' => 'text', 'length' => 64],
                    'community_type' => ['name' => _META_('mp.community.community_type'), 'type' => 'text', 'max' => 32, 'enum' => new CommunityType(), 'db_insert' => true],
                ],
                [
                    'auto_increment_id' => 'community_id',
                    'create_timestamp' => '_created_at',
                    'update_timestamp' => '_updated_at',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return Community
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return Community
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets updatedat
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->__get(self::_UPDATED_AT);
    }

    /**
     * Sets updatedat
     * @param string $value
     * @return Community
     */
    public function setUpdatedAt($value)
    {
        $this->__set(self::_UPDATED_AT, $value);

        return $this;
    }

    /**
     * Gets mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user_id
     * @param int $value
     * @return Community
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets 社区名称
     * @return string
     */
    public function getName()
    {
        return $this->__get(self::NAME);
    }

    /**
     * Sets 社区名称
     * @param string $value
     * @return Community
     */
    public function setName($value)
    {
        $this->__set(self::NAME, $value);

        return $this;
    }

    /**
     * Gets 热线电话
     * @return string
     */
    public function getPhone()
    {
        return $this->__get(self::PHONE);
    }

    /**
     * Sets 热线电话
     * @param string $value
     * @return Community
     */
    public function setPhone($value)
    {
        $this->__set(self::PHONE, $value);

        return $this;
    }

    /**
     * Gets 主送管理员email
     * @return string
     */
    public function getAdminEmail()
    {
        return $this->__get(self::ADMIN_EMAIL);
    }

    /**
     * Sets 主送管理员email
     * @param string $value
     * @return Community
     */
    public function setAdminEmail($value)
    {
        $this->__set(self::ADMIN_EMAIL, $value);

        return $this;
    }

    /**
     * Gets 抄送管理员email
     * @return string
     */
    public function getAdminCcEmail()
    {
        return $this->__get(self::ADMIN_CC_EMAIL);
    }

    /**
     * Sets 抄送管理员email
     * @param string $value
     * @return Community
     */
    public function setAdminCcEmail($value)
    {
        $this->__set(self::ADMIN_CC_EMAIL, $value);

        return $this;
    }

    /**
     * Gets 备注
     * @return string
     */
    public function getComment()
    {
        return $this->__get(self::COMMENT);
    }

    /**
     * Sets 备注
     * @param string $value
     * @return Community
     */
    public function setComment($value)
    {
        $this->__set(self::COMMENT, $value);

        return $this;
    }

    /**
     * Gets 是否是虚拟社区
     * @return bool
     */
    public function getIsVirtual()
    {
        return $this->__get(self::IS_VIRTUAL);
    }

    /**
     * Sets 是否是虚拟社区
     * @param bool $value
     * @return Community
     */
    public function setIsVirtual($value)
    {
        $this->__set(self::IS_VIRTUAL, $value);

        return $this;
    }

    /**
     * Gets 是否应用到app
     * @return bool
     */
    public function getIsApp()
    {
        return $this->__get(self::IS_APP);
    }

    /**
     * Sets 是否应用到app
     * @param bool $value
     * @return Community
     */
    public function setIsApp($value)
    {
        $this->__set(self::IS_APP, $value);

        return $this;
    }

    /**
     * Gets 是否有效
     * @return bool
     */
    public function getValid()
    {
        return $this->__get(self::VALID);
    }

    /**
     * Sets 是否有效
     * @param bool $value
     * @return Community
     */
    public function setValid($value)
    {
        $this->__set(self::VALID, $value);

        return $this;
    }

    /**
     * Gets 收费通知单提示
     * @return string
     */
    public function getBillComment()
    {
        return $this->__get(self::BILL_COMMENT);
    }

    /**
     * Sets 收费通知单提示
     * @param string $value
     * @return Community
     */
    public function setBillComment($value)
    {
        $this->__set(self::BILL_COMMENT, $value);

        return $this;
    }

    /**
     * Gets 收费通知单名称
     * @return string
     */
    public function getBillName()
    {
        return $this->__get(self::BILL_NAME);
    }

    /**
     * Sets 收费通知单名称
     * @param string $value
     * @return Community
     */
    public function setBillName($value)
    {
        $this->__set(self::BILL_NAME, $value);

        return $this;
    }

    /**
     * Gets 详细地址
     * @return string
     */
    public function getAddress()
    {
        return $this->__get(self::ADDRESS);
    }

    /**
     * Sets 详细地址
     * @param string $value
     * @return Community
     */
    public function setAddress($value)
    {
        $this->__set(self::ADDRESS, $value);

        return $this;
    }

    /**
     * Gets 所在省份
     * @return string
     */
    public function getProvince()
    {
        return $this->__get(self::PROVINCE);
    }

    /**
     * Sets 所在省份
     * @param string $value
     * @return Community
     */
    public function setProvince($value)
    {
        $this->__set(self::PROVINCE, $value);

        return $this;
    }

    /**
     * Gets 所在城市
     * @return string
     */
    public function getCity()
    {
        return $this->__get(self::CITY);
    }

    /**
     * Sets 所在城市
     * @param string $value
     * @return Community
     */
    public function setCity($value)
    {
        $this->__set(self::CITY, $value);

        return $this;
    }

    /**
     * Gets 所在区/县
     * @return string
     */
    public function getArea()
    {
        return $this->__get(self::AREA);
    }

    /**
     * Sets 所在区/县
     * @param string $value
     * @return Community
     */
    public function setArea($value)
    {
        $this->__set(self::AREA, $value);

        return $this;
    }

    /**
     * Gets 精度
     * @return string
     */
    public function getLongitude()
    {
        return $this->__get(self::LONGITUDE);
    }

    /**
     * Sets 精度
     * @param string $value
     * @return Community
     */
    public function setLongitude($value)
    {
        $this->__set(self::LONGITUDE, $value);

        return $this;
    }

    /**
     * Gets 纬度
     * @return string
     */
    public function getLatitude()
    {
        return $this->__get(self::LATITUDE);
    }

    /**
     * Sets 纬度
     * @param string $value
     * @return Community
     */
    public function setLatitude($value)
    {
        $this->__set(self::LATITUDE, $value);

        return $this;
    }

    /**
     * Gets 社区属性
     * @return string
     */
    public function getCommunityType()
    {
        return $this->__get(self::COMMUNITY_TYPE);
    }

    /**
     * Gets 社区属性 display name
     * @return string
     */
    public function getCommunityType_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('community_type');
        return $option['enum']::getDisplayName($this->__get(self::COMMUNITY_TYPE));
    }

    /**
     * Sets 社区属性
     * @param string $value
     * @return Community
     */
    public function setCommunityType($value)
    {
        $this->__set(self::COMMUNITY_TYPE, $value);

        return $this;
    }
}
?>