<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class CommunityReport extends Model
{
    const COMMUNITY_REPORT_ID = 'community_report_id';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const YMD = 'ymd';
    const ZHUHU_COUNT = 'zhuhu_count';
    const YEZHU_COUNT = 'yezhu_count';
    const ZHUHU_VERIFY = 'zhuhu_verify';
    const YEZHU_VERIFY = 'yezhu_verify';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'community_report',
                'community_report_id',
                [
                    'community_report_id' => ['name' => _META_('mp.community_report.community_report_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.community_report.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.community_report.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'ymd' => ['name' => _META_('mp.community_report.ymd'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'zhuhu_count' => ['name' => _META_('mp.community_report.zhuhu_count'), 'type' => 'int', 'length' => 10, 'db_insert' => true, 'required' => true],
                    'yezhu_count' => ['name' => _META_('mp.community_report.yezhu_count'), 'type' => 'int', 'length' => 10, 'db_insert' => true, 'required' => true],
                    'zhuhu_verify' => ['name' => _META_('mp.community_report.zhuhu_verify'), 'type' => 'int', 'length' => 10, 'db_insert' => true, 'required' => true],
                    'yezhu_verify' => ['name' => _META_('mp.community_report.yezhu_verify'), 'type' => 'int', 'length' => 10, 'db_insert' => true, 'required' => true],
                ],
                [
                    'auto_increment_id' => 'community_report_id',
                    'unique_keys' => [['community_id', 'ymd']],
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getCommunityReportID()
    {
        return $this->__get(self::COMMUNITY_REPORT_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return CommunityReport
     */
    public function setCommunityReportID($value)
    {
        $this->__set(self::COMMUNITY_REPORT_ID, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return CommunityReport
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return CommunityReport
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 年月日，示例20120525
     * @return int
     */
    public function getYmd()
    {
        return $this->__get(self::YMD);
    }

    /**
     * Sets 年月日，示例20120525
     * @param int $value
     * @return CommunityReport
     */
    public function setYmd($value)
    {
        $this->__set(self::YMD, $value);

        return $this;
    }

    /**
     * Gets 住户总数
     * @return int
     */
    public function getZhuhuCount()
    {
        return $this->__get(self::ZHUHU_COUNT);
    }

    /**
     * Sets 住户总数
     * @param int $value
     * @return CommunityReport
     */
    public function setZhuhuCount($value)
    {
        $this->__set(self::ZHUHU_COUNT, $value);

        return $this;
    }

    /**
     * Gets 业主总数
     * @return int
     */
    public function getYezhuCount()
    {
        return $this->__get(self::YEZHU_COUNT);
    }

    /**
     * Sets 业主总数
     * @param int $value
     * @return CommunityReport
     */
    public function setYezhuCount($value)
    {
        $this->__set(self::YEZHU_COUNT, $value);

        return $this;
    }

    /**
     * Gets 认证住户总数
     * @return int
     */
    public function getZhuhuVerify()
    {
        return $this->__get(self::ZHUHU_VERIFY);
    }

    /**
     * Sets 认证住户总数
     * @param int $value
     * @return CommunityReport
     */
    public function setZhuhuVerify($value)
    {
        $this->__set(self::ZHUHU_VERIFY, $value);

        return $this;
    }

    /**
     * Gets 认证业主总数
     * @return int
     */
    public function getYezhuVerify()
    {
        return $this->__get(self::YEZHU_VERIFY);
    }

    /**
     * Sets 认证业主总数
     * @param int $value
     * @return CommunityReport
     */
    public function setYezhuVerify($value)
    {
        $this->__set(self::YEZHU_VERIFY, $value);

        return $this;
    }
}
?>