<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class CommunityType implements ValidatorInterface
{
    const NONE = 'none';
    const PROCUREMENT_SUPPLY = 'procurement_supply';
    const PROCUREMENT_RESTAURANT = 'procurement_restaurant';
    const PROCUREMENT_TOTAL = 'procurement_total';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::NONE => _META_('mp.community_type.none'),
                self::PROCUREMENT_SUPPLY => _META_('mp.community_type.procurement_supply'),
                self::PROCUREMENT_RESTAURANT => _META_('mp.community_type.procurement_restaurant'),
                self::PROCUREMENT_TOTAL => _META_('mp.community_type.procurement_total'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::NONE;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}