<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class CommunityAdmin extends Model
{
    const COMMUNITY_ADMIN_ID = 'community_admin_id';
    const USERNAME = 'username';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const POWER = 'power';
    const ADMIN_USERNAME = 'admin_username';
    const ORDER_NOTIFY_TIME = 'order_notify_time';
    const ANSWER_NOTIFY_ID = 'answer_notify_id';
    const COMMENT = 'comment';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'community_admin',
                'community_admin_id',
                [
                    'community_admin_id' => ['name' => _META_('mp.community_admin.community_admin_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'username' => ['name' => _META_('mp.community_admin.username'), 'type' => 'text', 'length' => 128, 'required' => true],
                    'mp_user_id' => ['name' => _META_('mp.community_admin.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.community_admin.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'power' => ['name' => _META_('mp.community_admin.power'), 'type' => 'text', 'length' => 1024],
                    'admin_username' => ['name' => _META_('mp.community_admin.admin_username'), 'type' => 'text', 'length' => 128],
                    'order_notify_time' => ['name' => _META_('mp.community_admin.order_notify_time'), 'type' => 'datetime'],
                    'answer_notify_id' => ['name' => _META_('mp.community_admin.answer_notify_id'), 'type' => 'int', 'length' => 10],
                    'comment' => ['name' => _META_('mp.community_admin.comment'), 'type' => 'text'],
                ],
                [
                    'auto_increment_id' => 'community_admin_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getCommunityAdminID()
    {
        return $this->__get(self::COMMUNITY_ADMIN_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return CommunityAdmin
     */
    public function setCommunityAdminID($value)
    {
        $this->__set(self::COMMUNITY_ADMIN_ID, $value);

        return $this;
    }

    /**
     * Gets user.username
     * @return string
     */
    public function getUsername()
    {
        return $this->__get(self::USERNAME);
    }

    /**
     * Sets user.username
     * @param string $value
     * @return CommunityAdmin
     */
    public function setUsername($value)
    {
        $this->__set(self::USERNAME, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return CommunityAdmin
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return CommunityAdmin
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 权限
     * @return string
     */
    public function getPower()
    {
        return $this->__get(self::POWER);
    }

    /**
     * Sets 权限
     * @param string $value
     * @return CommunityAdmin
     */
    public function setPower($value)
    {
        $this->__set(self::POWER, $value);

        return $this;
    }

    /**
     * Gets 管理员帐号
     * @return string
     */
    public function getAdminUsername()
    {
        return $this->__get(self::ADMIN_USERNAME);
    }

    /**
     * Sets 管理员帐号
     * @param string $value
     * @return CommunityAdmin
     */
    public function setAdminUsername($value)
    {
        $this->__set(self::ADMIN_USERNAME, $value);

        return $this;
    }

    /**
     * Gets 新订单提醒时间
     * @return string
     */
    public function getOrderNotifyTime()
    {
        return $this->__get(self::ORDER_NOTIFY_TIME);
    }

    /**
     * Sets 新订单提醒时间
     * @param string $value
     * @return CommunityAdmin
     */
    public function setOrderNotifyTime($value)
    {
        $this->__set(self::ORDER_NOTIFY_TIME, $value);

        return $this;
    }

    /**
     * Gets 新问卷id
     * @return int
     */
    public function getAnswerNotifyID()
    {
        return $this->__get(self::ANSWER_NOTIFY_ID);
    }

    /**
     * Sets 新问卷id
     * @param int $value
     * @return CommunityAdmin
     */
    public function setAnswerNotifyID($value)
    {
        $this->__set(self::ANSWER_NOTIFY_ID, $value);

        return $this;
    }

    /**
     * Gets 备注
     * @return string
     */
    public function getComment()
    {
        return $this->__get(self::COMMENT);
    }

    /**
     * Sets 备注
     * @param string $value
     * @return CommunityAdmin
     */
    public function setComment($value)
    {
        $this->__set(self::COMMENT, $value);

        return $this;
    }
}
?>