<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class DirectoryPowerType implements ValidatorInterface
{
    const ALL = 'all';
    const REGISTER = 'register';
    const IDENTIFY = 'identify';
    const OTHER = 'other';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::ALL => _META_('mp.directory_power_type.all'),
                self::REGISTER => _META_('mp.directory_power_type.register'),
                self::IDENTIFY => _META_('mp.directory_power_type.identify'),
                self::OTHER => _META_('mp.directory_power_type.other'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::ALL;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}