<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class DirectoryWxUserVisit extends Model
{
    const DIRECTORY_WX_USER_VISIT_ID = 'directory_wx_user_visit_id';
    const DIRECTORY_ID = 'directory_id';
    const WX_USER_ID = 'wx_user_id';
    const LAST_ACCESS_YMD = 'last_access_ymd';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'directory_wx_user_visit',
                'directory_wx_user_visit_id',
                [
                    'directory_wx_user_visit_id' => ['name' => _META_('mp.directory_wx_user_visit.directory_wx_user_visit_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'directory_id' => ['name' => _META_('mp.directory_wx_user_visit.directory_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'wx_user_id' => ['name' => _META_('mp.directory_wx_user_visit.wx_user_id'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'last_access_ymd' => ['name' => _META_('mp.directory_wx_user_visit.last_access_ymd'), 'type' => 'int', 'length' => 10, 'required' => true],
                ],
                [
                    'auto_increment_id' => 'directory_wx_user_visit_id',
                    'unique_keys' => [['directory_id', 'wx_user_id']],
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getDirectoryWxUserVisitID()
    {
        return $this->__get(self::DIRECTORY_WX_USER_VISIT_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return DirectoryWxUserVisit
     */
    public function setDirectoryWxUserVisitID($value)
    {
        $this->__set(self::DIRECTORY_WX_USER_VISIT_ID, $value);

        return $this;
    }

    /**
     * Gets 二级目录id
     * @return int
     */
    public function getDirectoryID()
    {
        return $this->__get(self::DIRECTORY_ID);
    }

    /**
     * Sets 二级目录id
     * @param int $value
     * @return DirectoryWxUserVisit
     */
    public function setDirectoryID($value)
    {
        $this->__set(self::DIRECTORY_ID, $value);

        return $this;
    }

    /**
     * Gets wx_user.wx_user_id
     * @return string
     */
    public function getWxUserID()
    {
        return $this->__get(self::WX_USER_ID);
    }

    /**
     * Sets wx_user.wx_user_id
     * @param string $value
     * @return DirectoryWxUserVisit
     */
    public function setWxUserID($value)
    {
        $this->__set(self::WX_USER_ID, $value);

        return $this;
    }

    /**
     * Gets 上次访问日期
     * @return int
     */
    public function getLastAccessYmd()
    {
        return $this->__get(self::LAST_ACCESS_YMD);
    }

    /**
     * Sets 上次访问日期
     * @param int $value
     * @return DirectoryWxUserVisit
     */
    public function setLastAccessYmd($value)
    {
        $this->__set(self::LAST_ACCESS_YMD, $value);

        return $this;
    }
}
?>