<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class EmailRoleType implements ValidatorInterface
{
    const SEND_TO = 'send_to';
    const COPY_TO = 'copy_to';
    const BLIND_COPY_TO = 'blind_copy_to';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::SEND_TO => _META_('mp.email_role_type.send_to'),
                self::COPY_TO => _META_('mp.email_role_type.copy_to'),
                self::BLIND_COPY_TO => _META_('mp.email_role_type.blind_copy_to'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::SEND_TO;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}