<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class GroupSendItem extends Model
{
    const GROUP_SEND_ITEM_ID = 'group_send_item_id';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const TITLE = 'title';
    const CONTENT = 'content';
    const PIC_URL = 'pic_url';
    const DESCRIPTION = 'description';
    const CONTENT_SOURCE_URL = 'content_source_url';
    const AUTHOR = 'author';
    const SORT_NO = 'sort_no';
    const SHOW_COVER_PIC = 'show_cover_pic';
    const GROUP_SEND_ID = 'group_send_id';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'group_send_item',
                'group_send_item_id',
                [
                    'group_send_item_id' => ['name' => _META_('mp.group_send_item.group_send_item_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.group_send_item.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.group_send_item.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'title' => ['name' => _META_('mp.group_send_item.title'), 'type' => 'text', 'required' => true],
                    'content' => ['name' => _META_('mp.group_send_item.content'), 'type' => 'text'],
                    'pic_url' => ['name' => _META_('mp.group_send_item.pic_url'), 'type' => 'url'],
                    'description' => ['name' => _META_('mp.group_send_item.description'), 'type' => 'text'],
                    'content_source_url' => ['name' => _META_('mp.group_send_item.content_source_url'), 'type' => 'url'],
                    'author' => ['name' => _META_('mp.group_send_item.author'), 'type' => 'text', 'length' => 128],
                    'sort_no' => ['name' => _META_('mp.group_send_item.sort_no'), 'type' => 'float', 'db_insert' => true, 'required' => true],
                    'show_cover_pic' => ['name' => _META_('mp.group_send_item.show_cover_pic'), 'type' => 'bool', 'db_insert' => true, 'required' => true],
                    'group_send_id' => ['name' => _META_('mp.group_send_item.group_send_id'), 'type' => 'int', 'length' => 10],
                ],
                [
                    'auto_increment_id' => 'group_send_item_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getGroupSendItemID()
    {
        return $this->__get(self::GROUP_SEND_ITEM_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return GroupSendItem
     */
    public function setGroupSendItemID($value)
    {
        $this->__set(self::GROUP_SEND_ITEM_ID, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return GroupSendItem
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return GroupSendItem
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 消息标题
     * @return string
     */
    public function getTitle()
    {
        return $this->__get(self::TITLE);
    }

    /**
     * Sets 消息标题
     * @param string $value
     * @return GroupSendItem
     */
    public function setTitle($value)
    {
        $this->__set(self::TITLE, $value);

        return $this;
    }

    /**
     * Gets 消息内容
     * @return string
     */
    public function getContent()
    {
        return $this->__get(self::CONTENT);
    }

    /**
     * Sets 消息内容
     * @param string $value
     * @return GroupSendItem
     */
    public function setContent($value)
    {
        $this->__set(self::CONTENT, $value);

        return $this;
    }

    /**
     * Gets 消息图片url
     * @return string
     */
    public function getPicUrl()
    {
        return $this->__get(self::PIC_URL);
    }

    /**
     * Sets 消息图片url
     * @param string $value
     * @return GroupSendItem
     */
    public function setPicUrl($value)
    {
        $this->__set(self::PIC_URL, $value);

        return $this;
    }

    /**
     * Gets 内容摘要
     * @return string
     */
    public function getDescription()
    {
        return $this->__get(self::DESCRIPTION);
    }

    /**
     * Sets 内容摘要
     * @param string $value
     * @return GroupSendItem
     */
    public function setDescription($value)
    {
        $this->__set(self::DESCRIPTION, $value);

        return $this;
    }

    /**
     * Gets 原文链接
     * @return string
     */
    public function getContentSourceUrl()
    {
        return $this->__get(self::CONTENT_SOURCE_URL);
    }

    /**
     * Sets 原文链接
     * @param string $value
     * @return GroupSendItem
     */
    public function setContentSourceUrl($value)
    {
        $this->__set(self::CONTENT_SOURCE_URL, $value);

        return $this;
    }

    /**
     * Gets 作者
     * @return string
     */
    public function getAuthor()
    {
        return $this->__get(self::AUTHOR);
    }

    /**
     * Sets 作者
     * @param string $value
     * @return GroupSendItem
     */
    public function setAuthor($value)
    {
        $this->__set(self::AUTHOR, $value);

        return $this;
    }

    /**
     * Gets 排序
     * @return float
     */
    public function getSortNo()
    {
        return $this->__get(self::SORT_NO);
    }

    /**
     * Sets 排序
     * @param float $value
     * @return GroupSendItem
     */
    public function setSortNo($value)
    {
        $this->__set(self::SORT_NO, $value);

        return $this;
    }

    /**
     * Gets 是否显示封面
     * @return bool
     */
    public function getShowCoverPic()
    {
        return $this->__get(self::SHOW_COVER_PIC);
    }

    /**
     * Sets 是否显示封面
     * @param bool $value
     * @return GroupSendItem
     */
    public function setShowCoverPic($value)
    {
        $this->__set(self::SHOW_COVER_PIC, $value);

        return $this;
    }

    /**
     * Gets 群发信息id
     * @return int
     */
    public function getGroupSendID()
    {
        return $this->__get(self::GROUP_SEND_ID);
    }

    /**
     * Sets 群发信息id
     * @param int $value
     * @return GroupSendItem
     */
    public function setGroupSendID($value)
    {
        $this->__set(self::GROUP_SEND_ID, $value);

        return $this;
    }
}
?>