<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class GroupSendRangeType implements ValidatorInterface
{
    const SEND_TO_WHOLE_COMMUNITY = 'send_to_whole_community';
    const SEND_BY_HOUSE_NO = 'send_by_house_no';
    const SEND_TO_MP_USER = 'send_to_mp_user';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::SEND_TO_WHOLE_COMMUNITY => _META_('mp.group_send_range_type.send_to_whole_community'),
                self::SEND_BY_HOUSE_NO => _META_('mp.group_send_range_type.send_by_house_no'),
                self::SEND_TO_MP_USER => _META_('mp.group_send_range_type.send_to_mp_user'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::SEND_TO_WHOLE_COMMUNITY;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}