<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class GroupSend extends Model
{
    const GROUP_SEND_ID = 'group_send_id';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const TITLE = 'title';
    const CONTENT_VALUE = 'content_value';
    const MSG_ID = 'msg_id';
    const STATUS = 'status';
    const CREATE_TIME = 'create_time';
    const GROUP_SEND_NO = 'group_send_no';
    const GROUP_SEND_TIME = 'group_send_time';
    const GROUP_SEND_AUTHOR = 'group_send_author';
    const SEND_TYPE = 'send_type';
    const CONTENT_TYPE = 'content_type';
    const GROUP_SEND_RANGE = 'group_send_range';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'group_send',
                'group_send_id',
                [
                    'group_send_id' => ['name' => _META_('mp.group_send.group_send_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.group_send.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.group_send.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'title' => ['name' => _META_('mp.group_send.title'), 'type' => 'text', 'length' => 128, 'required' => true],
                    'content_value' => ['name' => _META_('mp.group_send.content_value'), 'type' => 'text'],
                    'msg_id' => ['name' => _META_('mp.group_send.msg_id'), 'type' => 'text', 'length' => 64],
                    'status' => ['name' => _META_('mp.group_send.status'), 'type' => 'text'],
                    'create_time' => ['name' => _META_('mp.group_send.create_time'), 'type' => 'datetime', 'required' => true],
                    'group_send_no' => ['name' => _META_('mp.group_send.group_send_no'), 'type' => 'text'],
                    'group_send_time' => ['name' => _META_('mp.group_send.group_send_time'), 'type' => 'datetime'],
                    'group_send_author' => ['name' => _META_('mp.group_send.group_send_author'), 'type' => 'text', 'length' => 128],
                    'send_type' => ['name' => _META_('mp.group_send.send_type'), 'type' => 'text', 'length' => 32],
                    'content_type' => ['name' => _META_('mp.group_send.content_type'), 'type' => 'text', 'max' => 32, 'required' => true, 'enum' => new GroupSendContentType(), 'db_insert' => true],
                    'group_send_range' => ['name' => _META_('mp.group_send.group_send_range'), 'type' => 'text', 'max' => 32, 'required' => true, 'enum' => new GroupSendRangeType(), 'db_insert' => true],
                ],
                [
                    'auto_increment_id' => 'group_send_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getGroupSendID()
    {
        return $this->__get(self::GROUP_SEND_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return GroupSend
     */
    public function setGroupSendID($value)
    {
        $this->__set(self::GROUP_SEND_ID, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return GroupSend
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return GroupSend
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 消息标题
     * @return string
     */
    public function getTitle()
    {
        return $this->__get(self::TITLE);
    }

    /**
     * Sets 消息标题
     * @param string $value
     * @return GroupSend
     */
    public function setTitle($value)
    {
        $this->__set(self::TITLE, $value);

        return $this;
    }

    /**
     * Gets 消息内容
     * @return string
     */
    public function getContentValue()
    {
        return $this->__get(self::CONTENT_VALUE);
    }

    /**
     * Sets 消息内容
     * @param string $value
     * @return GroupSend
     */
    public function setContentValue($value)
    {
        $this->__set(self::CONTENT_VALUE, $value);

        return $this;
    }

    /**
     * Gets 返回消息id
     * @return string
     */
    public function getMsgID()
    {
        return $this->__get(self::MSG_ID);
    }

    /**
     * Sets 返回消息id
     * @param string $value
     * @return GroupSend
     */
    public function setMsgID($value)
    {
        $this->__set(self::MSG_ID, $value);

        return $this;
    }

    /**
     * Gets 返回发送状态
     * @return string
     */
    public function getStatus()
    {
        return $this->__get(self::STATUS);
    }

    /**
     * Sets 返回发送状态
     * @param string $value
     * @return GroupSend
     */
    public function setStatus($value)
    {
        $this->__set(self::STATUS, $value);

        return $this;
    }

    /**
     * Gets 创建时间
     * @return string
     */
    public function getCreateTime()
    {
        return $this->__get(self::CREATE_TIME);
    }

    /**
     * Sets 创建时间
     * @param string $value
     * @return GroupSend
     */
    public function setCreateTime($value)
    {
        $this->__set(self::CREATE_TIME, $value);

        return $this;
    }

    /**
     * Gets 指定房间编号
     * @return string
     */
    public function getGroupSendNo()
    {
        return $this->__get(self::GROUP_SEND_NO);
    }

    /**
     * Sets 指定房间编号
     * @param string $value
     * @return GroupSend
     */
    public function setGroupSendNo($value)
    {
        $this->__set(self::GROUP_SEND_NO, $value);

        return $this;
    }

    /**
     * Gets 发布时间
     * @return string
     */
    public function getGroupSendTime()
    {
        return $this->__get(self::GROUP_SEND_TIME);
    }

    /**
     * Sets 发布时间
     * @param string $value
     * @return GroupSend
     */
    public function setGroupSendTime($value)
    {
        $this->__set(self::GROUP_SEND_TIME, $value);

        return $this;
    }

    /**
     * Gets 发布者
     * @return string
     */
    public function getGroupSendAuthor()
    {
        return $this->__get(self::GROUP_SEND_AUTHOR);
    }

    /**
     * Sets 发布者
     * @param string $value
     * @return GroupSend
     */
    public function setGroupSendAuthor($value)
    {
        $this->__set(self::GROUP_SEND_AUTHOR, $value);

        return $this;
    }

    /**
     * Gets 发送类型
     * @return string
     */
    public function getSendType()
    {
        return $this->__get(self::SEND_TYPE);
    }

    /**
     * Sets 发送类型
     * @param string $value
     * @return GroupSend
     */
    public function setSendType($value)
    {
        $this->__set(self::SEND_TYPE, $value);

        return $this;
    }

    /**
     * Gets 群发信息内容类型
     * @return string
     */
    public function getContentType()
    {
        return $this->__get(self::CONTENT_TYPE);
    }

    /**
     * Gets 群发信息内容类型 display name
     * @return string
     */
    public function getContentType_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('content_type');
        return $option['enum']::getDisplayName($this->__get(self::CONTENT_TYPE));
    }

    /**
     * Sets 群发信息内容类型
     * @param string $value
     * @return GroupSend
     */
    public function setContentType($value)
    {
        $this->__set(self::CONTENT_TYPE, $value);

        return $this;
    }

    /**
     * Gets 群发范围类型
     * @return string
     */
    public function getGroupSendRange()
    {
        return $this->__get(self::GROUP_SEND_RANGE);
    }

    /**
     * Gets 群发范围类型 display name
     * @return string
     */
    public function getGroupSendRange_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('group_send_range');
        return $option['enum']::getDisplayName($this->__get(self::GROUP_SEND_RANGE));
    }

    /**
     * Sets 群发范围类型
     * @param string $value
     * @return GroupSend
     */
    public function setGroupSendRange($value)
    {
        $this->__set(self::GROUP_SEND_RANGE, $value);

        return $this;
    }
}
?>