<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class MemberRelation implements ValidatorInterface
{
    const OWNER = 'owner';
    const KINSFOLK = 'kinsfolk';
    const LESSEE = 'lessee';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::OWNER => _META_('mp.member_relation.owner'),
                self::KINSFOLK => _META_('mp.member_relation.kinsfolk'),
                self::LESSEE => _META_('mp.member_relation.lessee'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::OWNER;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}