<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class MpArticle extends Model
{
    const MP_ARTICLE_ID = 'mp_article_id';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const TITLE = 'title';
    const SHARE_DESC = 'share_desc';
    const CONTENT = 'content';
    const SHOW_LIKE = 'show_like';
    const LIKE_COUNT = 'like_count';
    const USER_LEVEL = 'user_level';
    const REDIRECT = 'redirect';
    const REDIRECT_URL = 'redirect_url';
    const TAG = 'tag';
    const LAST_MODIFY_TIME = 'last_modify_time';
    const LAST_MODIFY_AUTHOR = 'last_modify_author';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'mp_article',
                'mp_article_id',
                [
                    'mp_article_id' => ['name' => _META_('mp.mp_article.mp_article_id'), 'type' => 'text', 'length' => 32, 'required' => true],
                    'mp_user_id' => ['name' => _META_('mp.mp_article.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.mp_article.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'title' => ['name' => _META_('mp.mp_article.title'), 'type' => 'text', 'length' => 255, 'required' => true],
                    'share_desc' => ['name' => _META_('mp.mp_article.share_desc'), 'type' => 'text', 'length' => 255, 'required' => true],
                    'content' => ['name' => _META_('mp.mp_article.content'), 'type' => 'text', 'required' => true],
                    'show_like' => ['name' => _META_('mp.mp_article.show_like'), 'type' => 'int', 'length' => 1, 'required' => true],
                    'like_count' => ['name' => _META_('mp.mp_article.like_count'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'user_level' => ['name' => _META_('mp.mp_article.user_level'), 'type' => 'text', 'length' => 128, 'db_insert' => true, 'required' => true],
                    'redirect' => ['name' => _META_('mp.mp_article.redirect'), 'type' => 'int', 'length' => 1, 'db_insert' => true, 'required' => true],
                    'redirect_url' => ['name' => _META_('mp.mp_article.redirect_url'), 'type' => 'text', 'length' => 1024],
                    'tag' => ['name' => _META_('mp.mp_article.tag'), 'type' => 'text', 'length' => 255],
                    'last_modify_time' => ['name' => _META_('mp.mp_article.last_modify_time'), 'type' => 'datetime', 'required' => true],
                    'last_modify_author' => ['name' => _META_('mp.mp_article.last_modify_author'), 'type' => 'text', 'length' => 128],
                ],
                [
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return string
     */
    public function getMpArticleID()
    {
        return $this->__get(self::MP_ARTICLE_ID);
    }

    /**
     * Sets id
     * @param string $value
     * @return MpArticle
     */
    public function setMpArticleID($value)
    {
        $this->__set(self::MP_ARTICLE_ID, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return MpArticle
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return MpArticle
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 文章标题
     * @return string
     */
    public function getTitle()
    {
        return $this->__get(self::TITLE);
    }

    /**
     * Sets 文章标题
     * @param string $value
     * @return MpArticle
     */
    public function setTitle($value)
    {
        $this->__set(self::TITLE, $value);

        return $this;
    }

    /**
     * Gets 分享时显示的文章摘要
     * @return string
     */
    public function getShareDesc()
    {
        return $this->__get(self::SHARE_DESC);
    }

    /**
     * Sets 分享时显示的文章摘要
     * @param string $value
     * @return MpArticle
     */
    public function setShareDesc($value)
    {
        $this->__set(self::SHARE_DESC, $value);

        return $this;
    }

    /**
     * Gets 文章内容
     * @return string
     */
    public function getContent()
    {
        return $this->__get(self::CONTENT);
    }

    /**
     * Sets 文章内容
     * @param string $value
     * @return MpArticle
     */
    public function setContent($value)
    {
        $this->__set(self::CONTENT, $value);

        return $this;
    }

    /**
     * Gets 是否显示喜欢和意见反馈
     * @return int
     */
    public function getShowLike()
    {
        return $this->__get(self::SHOW_LIKE);
    }

    /**
     * Sets 是否显示喜欢和意见反馈
     * @param int $value
     * @return MpArticle
     */
    public function setShowLike($value)
    {
        $this->__set(self::SHOW_LIKE, $value);

        return $this;
    }

    /**
     * Gets 已经点喜欢的人数
     * @return int
     */
    public function getLikeCount()
    {
        return $this->__get(self::LIKE_COUNT);
    }

    /**
     * Sets 已经点喜欢的人数
     * @param int $value
     * @return MpArticle
     */
    public function setLikeCount($value)
    {
        $this->__set(self::LIKE_COUNT, $value);

        return $this;
    }

    /**
     * Gets 逗号分隔的可阅读用户等级
     * @return string
     */
    public function getUserLevel()
    {
        return $this->__get(self::USER_LEVEL);
    }

    /**
     * Sets 逗号分隔的可阅读用户等级
     * @param string $value
     * @return MpArticle
     */
    public function setUserLevel($value)
    {
        $this->__set(self::USER_LEVEL, $value);

        return $this;
    }

    /**
     * Gets 是否跳转
     * @return int
     */
    public function getRedirect()
    {
        return $this->__get(self::REDIRECT);
    }

    /**
     * Sets 是否跳转
     * @param int $value
     * @return MpArticle
     */
    public function setRedirect($value)
    {
        $this->__set(self::REDIRECT, $value);

        return $this;
    }

    /**
     * Gets 跳转链接
     * @return string
     */
    public function getRedirectUrl()
    {
        return $this->__get(self::REDIRECT_URL);
    }

    /**
     * Sets 跳转链接
     * @param string $value
     * @return MpArticle
     */
    public function setRedirectUrl($value)
    {
        $this->__set(self::REDIRECT_URL, $value);

        return $this;
    }

    /**
     * Gets 标签
     * @return string
     */
    public function getTag()
    {
        return $this->__get(self::TAG);
    }

    /**
     * Sets 标签
     * @param string $value
     * @return MpArticle
     */
    public function setTag($value)
    {
        $this->__set(self::TAG, $value);

        return $this;
    }

    /**
     * Gets 最后修改时间
     * @return string
     */
    public function getLastModifyTime()
    {
        return $this->__get(self::LAST_MODIFY_TIME);
    }

    /**
     * Sets 最后修改时间
     * @param string $value
     * @return MpArticle
     */
    public function setLastModifyTime($value)
    {
        $this->__set(self::LAST_MODIFY_TIME, $value);

        return $this;
    }

    /**
     * Gets 最后修改人
     * @return string
     */
    public function getLastModifyAuthor()
    {
        return $this->__get(self::LAST_MODIFY_AUTHOR);
    }

    /**
     * Sets 最后修改人
     * @param string $value
     * @return MpArticle
     */
    public function setLastModifyAuthor($value)
    {
        $this->__set(self::LAST_MODIFY_AUTHOR, $value);

        return $this;
    }
}
?>