<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class MpFansCount extends Model
{
    const _UPDATED_AT = '_updated_at';
    const MP_USER_ID = 'mp_user_id';
    const FANS_COUNT = 'fans_count';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'mp_fans_count',
                'mp_user_id',
                [
                    '_updated_at' => ['name' => _META_('mp.mp_fans_count._updated_at'), 'type' => 'timestamp', 'required' => true, 'db_insert' => true, 'roc' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.mp_fans_count.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'fans_count' => ['name' => _META_('mp.mp_fans_count.fans_count'), 'type' => 'int', 'length' => 10, 'db_insert' => true, 'required' => true],
                ],
                [
                    'update_timestamp' => '_updated_at',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets updatedat
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->__get(self::_UPDATED_AT);
    }

    /**
     * Sets updatedat
     * @param string $value
     * @return MpFansCount
     */
    public function setUpdatedAt($value)
    {
        $this->__set(self::_UPDATED_AT, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return MpFansCount
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets 粉丝数
     * @return int
     */
    public function getFansCount()
    {
        return $this->__get(self::FANS_COUNT);
    }

    /**
     * Sets 粉丝数
     * @param int $value
     * @return MpFansCount
     */
    public function setFansCount($value)
    {
        $this->__set(self::FANS_COUNT, $value);

        return $this;
    }
}
?>