<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class MpRuleNewsItem extends Model
{
    const MP_RULE_NEWS_ITEM_ID = 'mp_rule_news_item_id';
    const _CREATED_AT = '_created_at';
    const MP_USER_ID = 'mp_user_id';
    const TITLE = 'title';
    const DESCRIPTION = 'description';
    const PIC_URL = 'pic_url';
    const URL = 'url';
    const SORT_NO = 'sort_no';
    const TOP_DIR_NO = 'top_dir_no';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'mp_rule_news_item',
                'mp_rule_news_item_id',
                [
                    'mp_rule_news_item_id' => ['name' => _META_('mp.mp_rule_news_item.mp_rule_news_item_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('mp.mp_rule_news_item._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.mp_rule_news_item.mp_user_id'), 'type' => 'int', 'length' => 10, 'db_insert' => true, 'required' => true],
                    'title' => ['name' => _META_('mp.mp_rule_news_item.title'), 'type' => 'text', 'required' => true],
                    'description' => ['name' => _META_('mp.mp_rule_news_item.description'), 'type' => 'text'],
                    'pic_url' => ['name' => _META_('mp.mp_rule_news_item.pic_url'), 'type' => 'url'],
                    'url' => ['name' => _META_('mp.mp_rule_news_item.url'), 'type' => 'url'],
                    'sort_no' => ['name' => _META_('mp.mp_rule_news_item.sort_no'), 'type' => 'float', 'db_insert' => true, 'required' => true],
                    'top_dir_no' => ['name' => _META_('mp.mp_rule_news_item.top_dir_no'), 'type' => 'int', 'length' => 10],
                ],
                [
                    'auto_increment_id' => 'mp_rule_news_item_id',
                    'create_timestamp' => '_created_at',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getMpRuleNewsItemID()
    {
        return $this->__get(self::MP_RULE_NEWS_ITEM_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return MpRuleNewsItem
     */
    public function setMpRuleNewsItemID($value)
    {
        $this->__set(self::MP_RULE_NEWS_ITEM_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return MpRuleNewsItem
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return MpRuleNewsItem
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets 标题
     * @return string
     */
    public function getTitle()
    {
        return $this->__get(self::TITLE);
    }

    /**
     * Sets 标题
     * @param string $value
     * @return MpRuleNewsItem
     */
    public function setTitle($value)
    {
        $this->__set(self::TITLE, $value);

        return $this;
    }

    /**
     * Gets 描述
     * @return string
     */
    public function getDescription()
    {
        return $this->__get(self::DESCRIPTION);
    }

    /**
     * Sets 描述
     * @param string $value
     * @return MpRuleNewsItem
     */
    public function setDescription($value)
    {
        $this->__set(self::DESCRIPTION, $value);

        return $this;
    }

    /**
     * Gets 图片url
     * @return string
     */
    public function getPicUrl()
    {
        return $this->__get(self::PIC_URL);
    }

    /**
     * Sets 图片url
     * @param string $value
     * @return MpRuleNewsItem
     */
    public function setPicUrl($value)
    {
        $this->__set(self::PIC_URL, $value);

        return $this;
    }

    /**
     * Gets 图文消息url
     * @return string
     */
    public function getUrl()
    {
        return $this->__get(self::URL);
    }

    /**
     * Sets 图文消息url
     * @param string $value
     * @return MpRuleNewsItem
     */
    public function setUrl($value)
    {
        $this->__set(self::URL, $value);

        return $this;
    }

    /**
     * Gets 排序id
     * @return float
     */
    public function getSortNo()
    {
        return $this->__get(self::SORT_NO);
    }

    /**
     * Sets 排序id
     * @param float $value
     * @return MpRuleNewsItem
     */
    public function setSortNo($value)
    {
        $this->__set(self::SORT_NO, $value);

        return $this;
    }

    /**
     * Gets 一级目录编号
     * @return int
     */
    public function getTopDirNo()
    {
        return $this->__get(self::TOP_DIR_NO);
    }

    /**
     * Sets 一级目录编号
     * @param int $value
     * @return MpRuleNewsItem
     */
    public function setTopDirNo($value)
    {
        $this->__set(self::TOP_DIR_NO, $value);

        return $this;
    }
}
?>