<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class MpUserConfigTypeType implements ValidatorInterface
{
    const TEXT = 'text';
    const BOOL = 'bool';
    const IMG = 'img';
    const URL = 'url';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::TEXT => _META_('mp.mp_user_config_type_type.text'),
                self::BOOL => _META_('mp.mp_user_config_type_type.bool'),
                self::IMG => _META_('mp.mp_user_config_type_type.img'),
                self::URL => _META_('mp.mp_user_config_type_type.url'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::TEXT;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}