<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class MpUserConfigType implements ValidatorInterface
{
    const BIRTHDAY_TITLE = 'birthday_title';
    const BIRTHDAY_DESCRIPTION = 'birthday_description';
    const BIRTHDAY_PIC_URL = 'birthday_pic_url';
    const BIRTHDAY_ARTICLE_URL = 'birthday_article_url';
    const CS_ANSWER = 'cs_answer';
    const CS_CLICK_WX_MENU_HINT = 'cs_click_wx_menu_hint';
    const VERIFY_CODE_ID = 'verify_code_id';
    const TEMPLATE_MESSAGE_NOTIFY_ID = 'template_message_notify_id';
    const TEMPLATE_ORDER_NOTIFY_ID = 'template_order_notify_id';
    const TEMPLATE_SERVICE_NOTIFY_ID = 'template_service_notify_id';
    const TEMPLATE_FIANCE_NOTIFY_ID = 'template_fiance_notify_id';
    const SUBSCRIBE_BOOL_NEWS = 'subscribe_bool_news';
    const SUBSCRIBE_TITLE = 'subscribe_title';
    const SUBSCRIBE_DESCRIPTION = 'subscribe_description';
    const SUBSCRIBE_PIC = 'subscribe_pic';
    const SUBSCRIBE_URL = 'subscribe_url';
    const WX_PAY = 'wx_pay';
    const MP_USER_NAME_LINK = 'mp_user_name_link';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::BIRTHDAY_TITLE => _META_('mp.mp_user_config_type.birthday_title'),
                self::BIRTHDAY_DESCRIPTION => _META_('mp.mp_user_config_type.birthday_description'),
                self::BIRTHDAY_PIC_URL => _META_('mp.mp_user_config_type.birthday_pic_url'),
                self::BIRTHDAY_ARTICLE_URL => _META_('mp.mp_user_config_type.birthday_article_url'),
                self::CS_ANSWER => _META_('mp.mp_user_config_type.cs_answer'),
                self::CS_CLICK_WX_MENU_HINT => _META_('mp.mp_user_config_type.cs_click_wx_menu_hint'),
                self::VERIFY_CODE_ID => _META_('mp.mp_user_config_type.verify_code_id'),
                self::TEMPLATE_MESSAGE_NOTIFY_ID => _META_('mp.mp_user_config_type.template_message_notify_id'),
                self::TEMPLATE_ORDER_NOTIFY_ID => _META_('mp.mp_user_config_type.template_order_notify_id'),
                self::TEMPLATE_SERVICE_NOTIFY_ID => _META_('mp.mp_user_config_type.template_service_notify_id'),
                self::TEMPLATE_FIANCE_NOTIFY_ID => _META_('mp.mp_user_config_type.template_fiance_notify_id'),
                self::SUBSCRIBE_BOOL_NEWS => _META_('mp.mp_user_config_type.subscribe_bool_news'),
                self::SUBSCRIBE_TITLE => _META_('mp.mp_user_config_type.subscribe_title'),
                self::SUBSCRIBE_DESCRIPTION => _META_('mp.mp_user_config_type.subscribe_description'),
                self::SUBSCRIBE_PIC => _META_('mp.mp_user_config_type.subscribe_pic'),
                self::SUBSCRIBE_URL => _META_('mp.mp_user_config_type.subscribe_url'),
                self::WX_PAY => _META_('mp.mp_user_config_type.wx_pay'),
                self::MP_USER_NAME_LINK => _META_('mp.mp_user_config_type.mp_user_name_link'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::BIRTHDAY_TITLE;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}