<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class OrderStatus implements ValidatorInterface
{
    const DEFAULT_STATUS = 'default_status';
    const SUBMITTED_TO_PAY = 'submitted_to_pay';
    const PAID_TO_VERIFY = 'paid_to_verify';
    const VERIFIED_TO_SHIP = 'verified_to_ship';
    const DISPATCHED = 'dispatched';
    const ARRIVED = 'arrived';
    const FINISHED = 'finished';
    const CLOSED = 'closed';
    const REJECT = 'reject';
    const REFUND = 'refund';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::DEFAULT_STATUS => _META_('mp.order_status.default_status'),
                self::SUBMITTED_TO_PAY => _META_('mp.order_status.submitted_to_pay'),
                self::PAID_TO_VERIFY => _META_('mp.order_status.paid_to_verify'),
                self::VERIFIED_TO_SHIP => _META_('mp.order_status.verified_to_ship'),
                self::DISPATCHED => _META_('mp.order_status.dispatched'),
                self::ARRIVED => _META_('mp.order_status.arrived'),
                self::FINISHED => _META_('mp.order_status.finished'),
                self::CLOSED => _META_('mp.order_status.closed'),
                self::REJECT => _META_('mp.order_status.reject'),
                self::REFUND => _META_('mp.order_status.refund'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::DEFAULT_STATUS;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}