<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class OwnerLessee extends Model
{
    const OWNER_LESSEE_ID = 'owner_lessee_id';
    const LESSEE_WX_USER_ID = 'lessee_wx_user_id';
    const OWNER_WX_USER_ID = 'owner_wx_user_id';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'owner_lessee',
                'owner_lessee_id',
                [
                    'owner_lessee_id' => ['name' => _META_('mp.owner_lessee.owner_lessee_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'lessee_wx_user_id' => ['name' => _META_('mp.owner_lessee.lessee_wx_user_id'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'owner_wx_user_id' => ['name' => _META_('mp.owner_lessee.owner_wx_user_id'), 'type' => 'text', 'length' => 64, 'required' => true],
                ],
                [
                    'auto_increment_id' => 'owner_lessee_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getOwnerLesseeID()
    {
        return $this->__get(self::OWNER_LESSEE_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return OwnerLessee
     */
    public function setOwnerLesseeID($value)
    {
        $this->__set(self::OWNER_LESSEE_ID, $value);

        return $this;
    }

    /**
     * Gets lesseeopenid
     * @return string
     */
    public function getLesseeWxUserID()
    {
        return $this->__get(self::LESSEE_WX_USER_ID);
    }

    /**
     * Sets lesseeopenid
     * @param string $value
     * @return OwnerLessee
     */
    public function setLesseeWxUserID($value)
    {
        $this->__set(self::LESSEE_WX_USER_ID, $value);

        return $this;
    }

    /**
     * Gets owneropenid
     * @return string
     */
    public function getOwnerWxUserID()
    {
        return $this->__get(self::OWNER_WX_USER_ID);
    }

    /**
     * Sets owneropenid
     * @param string $value
     * @return OwnerLessee
     */
    public function setOwnerWxUserID($value)
    {
        $this->__set(self::OWNER_WX_USER_ID, $value);

        return $this;
    }
}
?>