<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class ProcurementCart extends Model
{
    const PROCUREMENT_CART_ID = 'procurement_cart_id';
    const _CREATED_AT = '_created_at';
    const MP_USER_ID = 'mp_user_id';
    const STORE_ID = 'store_id';
    const WX_USER_ID = 'wx_user_id';
    const PART_ID = 'part_id';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'procurement_cart',
                'procurement_cart_id',
                [
                    'procurement_cart_id' => ['name' => _META_('mp.procurement_cart.procurement_cart_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('mp.procurement_cart._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.procurement_cart.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'store_id' => ['name' => _META_('mp.procurement_cart.store_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'wx_user_id' => ['name' => _META_('mp.procurement_cart.wx_user_id'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'part_id' => ['name' => _META_('mp.procurement_cart.part_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                ],
                [
                    'auto_increment_id' => 'procurement_cart_id',
                    'create_timestamp' => '_created_at',
                    'unique_keys' => [['mp_user_id', 'store_id', 'wx_user_id', 'part_id']],
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getProcurementCartID()
    {
        return $this->__get(self::PROCUREMENT_CART_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return ProcurementCart
     */
    public function setProcurementCartID($value)
    {
        $this->__set(self::PROCUREMENT_CART_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return ProcurementCart
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets 公众账号id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets 公众账号id
     * @param int $value
     * @return ProcurementCart
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets 商城id
     * @return int
     */
    public function getStoreID()
    {
        return $this->__get(self::STORE_ID);
    }

    /**
     * Sets 商城id
     * @param int $value
     * @return ProcurementCart
     */
    public function setStoreID($value)
    {
        $this->__set(self::STORE_ID, $value);

        return $this;
    }

    /**
     * Gets 微信用户id
     * @return string
     */
    public function getWxUserID()
    {
        return $this->__get(self::WX_USER_ID);
    }

    /**
     * Sets 微信用户id
     * @param string $value
     * @return ProcurementCart
     */
    public function setWxUserID($value)
    {
        $this->__set(self::WX_USER_ID, $value);

        return $this;
    }

    /**
     * Gets 档口id
     * @return int
     */
    public function getPartID()
    {
        return $this->__get(self::PART_ID);
    }

    /**
     * Sets 档口id
     * @param int $value
     * @return ProcurementCart
     */
    public function setPartID($value)
    {
        $this->__set(self::PART_ID, $value);

        return $this;
    }
}
?>