<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class ProcurementPowerType implements ValidatorInterface
{
    const NONE = 'none';
    const ORDER = 'order';
    const EXAMINE = 'examine';
    const REFUND = 'refund';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::NONE => _META_('mp.procurement_power_type.none'),
                self::ORDER => _META_('mp.procurement_power_type.order'),
                self::EXAMINE => _META_('mp.procurement_power_type.examine'),
                self::REFUND => _META_('mp.procurement_power_type.refund'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::NONE;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}