<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class ProcurementCartDetail extends Model
{
    const PROCUREMENT_CART_DETAIL_ID = 'procurement_cart_detail_id';
    const _CREATED_AT = '_created_at';
    const CART_ID = 'cart_id';
    const PRODUCT_ID = 'product_id';
    const PART_ID = 'part_id';
    const COUNT = 'count';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'procurement_cart_detail',
                'procurement_cart_detail_id',
                [
                    'procurement_cart_detail_id' => ['name' => _META_('mp.procurement_cart_detail.procurement_cart_detail_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('mp.procurement_cart_detail._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'cart_id' => ['name' => _META_('mp.procurement_cart_detail.cart_id'), 'type' => 'text', 'length' => 32, 'required' => true],
                    'product_id' => ['name' => _META_('mp.procurement_cart_detail.product_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'part_id' => ['name' => _META_('mp.procurement_cart_detail.part_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'count' => ['name' => _META_('mp.procurement_cart_detail.count'), 'type' => 'float', 'length' => 10, 'db_insert' => true, 'required' => true],
                ],
                [
                    'auto_increment_id' => 'procurement_cart_detail_id',
                    'create_timestamp' => '_created_at',
                    'unique_keys' => [['cart_id', 'product_id', 'part_id']],
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getProcurementCartDetailID()
    {
        return $this->__get(self::PROCUREMENT_CART_DETAIL_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return ProcurementCartDetail
     */
    public function setProcurementCartDetailID($value)
    {
        $this->__set(self::PROCUREMENT_CART_DETAIL_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return ProcurementCartDetail
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets 购物车id
     * @return string
     */
    public function getCartID()
    {
        return $this->__get(self::CART_ID);
    }

    /**
     * Sets 购物车id
     * @param string $value
     * @return ProcurementCartDetail
     */
    public function setCartID($value)
    {
        $this->__set(self::CART_ID, $value);

        return $this;
    }

    /**
     * Gets 产品id
     * @return int
     */
    public function getProductID()
    {
        return $this->__get(self::PRODUCT_ID);
    }

    /**
     * Sets 产品id
     * @param int $value
     * @return ProcurementCartDetail
     */
    public function setProductID($value)
    {
        $this->__set(self::PRODUCT_ID, $value);

        return $this;
    }

    /**
     * Gets 档口id
     * @return int
     */
    public function getPartID()
    {
        return $this->__get(self::PART_ID);
    }

    /**
     * Sets 档口id
     * @param int $value
     * @return ProcurementCartDetail
     */
    public function setPartID($value)
    {
        $this->__set(self::PART_ID, $value);

        return $this;
    }

    /**
     * Gets 数量
     * @return float
     */
    public function getCount()
    {
        return $this->__get(self::COUNT);
    }

    /**
     * Sets 数量
     * @param float $value
     * @return ProcurementCartDetail
     */
    public function setCount($value)
    {
        $this->__set(self::COUNT, $value);

        return $this;
    }
}
?>