<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class ProcurementOrderChangeDetail extends Model
{
    const PROCUREMENT_ORDER_CHANGE_DETAIL_ID = 'procurement_order_change_detail_id';
    const ORDER_ID = 'order_id';
    const PRODUCT_ID = 'product_id';
    const IMG_URL = 'img_url';
    const PRICE = 'price';
    const TITLE = 'title';
    const DESCRIPTION = 'description';
    const COUNT = 'count';
    const CHEF_COUNT = 'chef_count';
    const PART_ID = 'part_id';
    const PRODUCT_UNIT = 'product_unit';
    const STATUS = 'status';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'procurement_order_change_detail',
                'procurement_order_change_detail_id',
                [
                    'procurement_order_change_detail_id' => ['name' => _META_('mp.procurement_order_change_detail.procurement_order_change_detail_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'order_id' => ['name' => _META_('mp.procurement_order_change_detail.order_id'), 'type' => 'text', 'length' => 32, 'required' => true],
                    'product_id' => ['name' => _META_('mp.procurement_order_change_detail.product_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'img_url' => ['name' => _META_('mp.procurement_order_change_detail.img_url'), 'type' => 'url'],
                    'price' => ['name' => _META_('mp.procurement_order_change_detail.price'), 'type' => 'money', 'db_insert' => true, 'precision' => 2, 'required' => true],
                    'title' => ['name' => _META_('mp.procurement_order_change_detail.title'), 'type' => 'text', 'length' => 128, 'required' => true],
                    'description' => ['name' => _META_('mp.procurement_order_change_detail.description'), 'type' => 'text', 'length' => 128],
                    'count' => ['name' => _META_('mp.procurement_order_change_detail.count'), 'type' => 'float', 'length' => 10],
                    'chef_count' => ['name' => _META_('mp.procurement_order_change_detail.chef_count'), 'type' => 'float', 'length' => 10, 'db_insert' => true],
                    'part_id' => ['name' => _META_('mp.procurement_order_change_detail.part_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'product_unit' => ['name' => _META_('mp.procurement_order_change_detail.product_unit'), 'type' => 'text', 'max' => 32, 'enum' => new ProductUnitType(), 'db_insert' => true],
                    'status' => ['name' => _META_('mp.procurement_order_change_detail.status'), 'type' => 'text', 'max' => 32, 'required' => true, 'enum' => new ProcurementOrderStatus(), 'db_insert' => true],
                ],
                [
                    'auto_increment_id' => 'procurement_order_change_detail_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getProcurementOrderChangeDetailID()
    {
        return $this->__get(self::PROCUREMENT_ORDER_CHANGE_DETAIL_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return ProcurementOrderChangeDetail
     */
    public function setProcurementOrderChangeDetailID($value)
    {
        $this->__set(self::PROCUREMENT_ORDER_CHANGE_DETAIL_ID, $value);

        return $this;
    }

    /**
     * Gets 订单号
     * @return string
     */
    public function getOrderID()
    {
        return $this->__get(self::ORDER_ID);
    }

    /**
     * Sets 订单号
     * @param string $value
     * @return ProcurementOrderChangeDetail
     */
    public function setOrderID($value)
    {
        $this->__set(self::ORDER_ID, $value);

        return $this;
    }

    /**
     * Gets 产品id
     * @return int
     */
    public function getProductID()
    {
        return $this->__get(self::PRODUCT_ID);
    }

    /**
     * Sets 产品id
     * @param int $value
     * @return ProcurementOrderChangeDetail
     */
    public function setProductID($value)
    {
        $this->__set(self::PRODUCT_ID, $value);

        return $this;
    }

    /**
     * Gets 图片地址
     * @return string
     */
    public function getImgUrl()
    {
        return $this->__get(self::IMG_URL);
    }

    /**
     * Sets 图片地址
     * @param string $value
     * @return ProcurementOrderChangeDetail
     */
    public function setImgUrl($value)
    {
        $this->__set(self::IMG_URL, $value);

        return $this;
    }

    /**
     * Gets 价格
     * @return float
     */
    public function getPrice()
    {
        return $this->__get(self::PRICE);
    }

    /**
     * Sets 价格
     * @param float $value
     * @return ProcurementOrderChangeDetail
     */
    public function setPrice($value)
    {
        $this->__set(self::PRICE, $value);

        return $this;
    }

    /**
     * Gets 产品名称
     * @return string
     */
    public function getTitle()
    {
        return $this->__get(self::TITLE);
    }

    /**
     * Sets 产品名称
     * @param string $value
     * @return ProcurementOrderChangeDetail
     */
    public function setTitle($value)
    {
        $this->__set(self::TITLE, $value);

        return $this;
    }

    /**
     * Gets 产品描述
     * @return string
     */
    public function getDescription()
    {
        return $this->__get(self::DESCRIPTION);
    }

    /**
     * Sets 产品描述
     * @param string $value
     * @return ProcurementOrderChangeDetail
     */
    public function setDescription($value)
    {
        $this->__set(self::DESCRIPTION, $value);

        return $this;
    }

    /**
     * Gets 数量
     * @return float
     */
    public function getCount()
    {
        return $this->__get(self::COUNT);
    }

    /**
     * Sets 数量
     * @param float $value
     * @return ProcurementOrderChangeDetail
     */
    public function setCount($value)
    {
        $this->__set(self::COUNT, $value);

        return $this;
    }

    /**
     * Gets 订货员改变次数
     * @return float
     */
    public function getChefCount()
    {
        return $this->__get(self::CHEF_COUNT);
    }

    /**
     * Sets 订货员改变次数
     * @param float $value
     * @return ProcurementOrderChangeDetail
     */
    public function setChefCount($value)
    {
        $this->__set(self::CHEF_COUNT, $value);

        return $this;
    }

    /**
     * Gets 档口id
     * @return int
     */
    public function getPartID()
    {
        return $this->__get(self::PART_ID);
    }

    /**
     * Sets 档口id
     * @param int $value
     * @return ProcurementOrderChangeDetail
     */
    public function setPartID($value)
    {
        $this->__set(self::PART_ID, $value);

        return $this;
    }

    /**
     * Gets 单位
     * @return string
     */
    public function getProductUnit()
    {
        return $this->__get(self::PRODUCT_UNIT);
    }

    /**
     * Gets 单位 display name
     * @return string
     */
    public function getProductUnit_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('product_unit');
        return $option['enum']::getDisplayName($this->__get(self::PRODUCT_UNIT));
    }

    /**
     * Sets 单位
     * @param string $value
     * @return ProcurementOrderChangeDetail
     */
    public function setProductUnit($value)
    {
        $this->__set(self::PRODUCT_UNIT, $value);

        return $this;
    }

    /**
     * Gets 交易状态
     * @return string
     */
    public function getStatus()
    {
        return $this->__get(self::STATUS);
    }

    /**
     * Gets 交易状态 display name
     * @return string
     */
    public function getStatus_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('status');
        return $option['enum']::getDisplayName($this->__get(self::STATUS));
    }

    /**
     * Sets 交易状态
     * @param string $value
     * @return ProcurementOrderChangeDetail
     */
    public function setStatus($value)
    {
        $this->__set(self::STATUS, $value);

        return $this;
    }
}
?>