<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class ProcurementOrder extends Model
{
    const ORDER_ID = 'order_id';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const WX_USER_ID = 'wx_user_id';
    const COMMENT = 'comment';
    const CUSTOMER_NAME = 'customer_name';
    const TEL = 'tel';
    const ADDRESS = 'address';
    const TOTAL_PRICE = 'total_price';
    const TOTAL_NUM = 'total_num';
    const CREATE_TIME = 'create_time';
    const FINISH_TIME = 'finish_time';
    const BOUND_COMMUNITY_ID = 'bound_community_id';
    const BOUND_STORE_ID = 'bound_store_id';
    const STORE_ID = 'store_id';
    const CATEGORY_ID = 'category_id';
    const REFUND_ORDER_ID = 'refund_order_id';
    const REFUND_DESCRIBE = 'refund_describe';
    const REFUND_IMG_FIRST = 'refund_img_first';
    const REFUND_IMG_SECOND = 'refund_img_second';
    const REFUND_IMG_THIRD = 'refund_img_third';
    const ORDER_SELF = 'order_self';
    const STATUS = 'status';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'procurement_order',
                'order_id',
                [
                    'order_id' => ['name' => _META_('mp.procurement_order.order_id'), 'type' => 'text', 'length' => 32, 'required' => true],
                    'mp_user_id' => ['name' => _META_('mp.procurement_order.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.procurement_order.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'wx_user_id' => ['name' => _META_('mp.procurement_order.wx_user_id'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'comment' => ['name' => _META_('mp.procurement_order.comment'), 'type' => 'text', 'length' => 255],
                    'customer_name' => ['name' => _META_('mp.procurement_order.customer_name'), 'type' => 'text', 'length' => 64],
                    'tel' => ['name' => _META_('mp.procurement_order.tel'), 'type' => 'text', 'length' => 64],
                    'address' => ['name' => _META_('mp.procurement_order.address'), 'type' => 'text', 'length' => 255],
                    'total_price' => ['name' => _META_('mp.procurement_order.total_price'), 'type' => 'money', 'precision' => 2, 'required' => true],
                    'total_num' => ['name' => _META_('mp.procurement_order.total_num'), 'type' => 'int', 'length' => 10, 'db_insert' => true, 'required' => true],
                    'create_time' => ['name' => _META_('mp.procurement_order.create_time'), 'type' => 'datetime', 'required' => true],
                    'finish_time' => ['name' => _META_('mp.procurement_order.finish_time'), 'type' => 'datetime'],
                    'bound_community_id' => ['name' => _META_('mp.procurement_order.bound_community_id'), 'type' => 'int', 'length' => 10],
                    'bound_store_id' => ['name' => _META_('mp.procurement_order.bound_store_id'), 'type' => 'int', 'length' => 10],
                    'store_id' => ['name' => _META_('mp.procurement_order.store_id'), 'type' => 'int', 'length' => 10],
                    'category_id' => ['name' => _META_('mp.procurement_order.category_id'), 'type' => 'int', 'length' => 10],
                    'refund_order_id' => ['name' => _META_('mp.procurement_order.refund_order_id'), 'type' => 'text', 'length' => 32],
                    'refund_describe' => ['name' => _META_('mp.procurement_order.refund_describe'), 'type' => 'text'],
                    'refund_img_first' => ['name' => _META_('mp.procurement_order.refund_img_first'), 'type' => 'url'],
                    'refund_img_second' => ['name' => _META_('mp.procurement_order.refund_img_second'), 'type' => 'url'],
                    'refund_img_third' => ['name' => _META_('mp.procurement_order.refund_img_third'), 'type' => 'url'],
                    'order_self' => ['name' => _META_('mp.procurement_order.order_self'), 'type' => 'text', 'length' => 32, 'db_insert' => true],
                    'status' => ['name' => _META_('mp.procurement_order.status'), 'type' => 'text', 'max' => 32, 'required' => true, 'enum' => new ProcurementOrderStatus(), 'db_insert' => true],
                ],
                [
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets 订单号
     * @return string
     */
    public function getOrderID()
    {
        return $this->__get(self::ORDER_ID);
    }

    /**
     * Sets 订单号
     * @param string $value
     * @return ProcurementOrder
     */
    public function setOrderID($value)
    {
        $this->__set(self::ORDER_ID, $value);

        return $this;
    }

    /**
     * Gets 公众账号id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets 公众账号id
     * @param int $value
     * @return ProcurementOrder
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return ProcurementOrder
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 微信用户id
     * @return string
     */
    public function getWxUserID()
    {
        return $this->__get(self::WX_USER_ID);
    }

    /**
     * Sets 微信用户id
     * @param string $value
     * @return ProcurementOrder
     */
    public function setWxUserID($value)
    {
        $this->__set(self::WX_USER_ID, $value);

        return $this;
    }

    /**
     * Gets 备注
     * @return string
     */
    public function getComment()
    {
        return $this->__get(self::COMMENT);
    }

    /**
     * Sets 备注
     * @param string $value
     * @return ProcurementOrder
     */
    public function setComment($value)
    {
        $this->__set(self::COMMENT, $value);

        return $this;
    }

    /**
     * Gets 下单者
     * @return string
     */
    public function getCustomerName()
    {
        return $this->__get(self::CUSTOMER_NAME);
    }

    /**
     * Sets 下单者
     * @param string $value
     * @return ProcurementOrder
     */
    public function setCustomerName($value)
    {
        $this->__set(self::CUSTOMER_NAME, $value);

        return $this;
    }

    /**
     * Gets 电话
     * @return string
     */
    public function getTel()
    {
        return $this->__get(self::TEL);
    }

    /**
     * Sets 电话
     * @param string $value
     * @return ProcurementOrder
     */
    public function setTel($value)
    {
        $this->__set(self::TEL, $value);

        return $this;
    }

    /**
     * Gets 地址
     * @return string
     */
    public function getAddress()
    {
        return $this->__get(self::ADDRESS);
    }

    /**
     * Sets 地址
     * @param string $value
     * @return ProcurementOrder
     */
    public function setAddress($value)
    {
        $this->__set(self::ADDRESS, $value);

        return $this;
    }

    /**
     * Gets 订单总价
     * @return float
     */
    public function getTotalPrice()
    {
        return $this->__get(self::TOTAL_PRICE);
    }

    /**
     * Sets 订单总价
     * @param float $value
     * @return ProcurementOrder
     */
    public function setTotalPrice($value)
    {
        $this->__set(self::TOTAL_PRICE, $value);

        return $this;
    }

    /**
     * Gets 订单总数量
     * @return int
     */
    public function getTotalNum()
    {
        return $this->__get(self::TOTAL_NUM);
    }

    /**
     * Sets 订单总数量
     * @param int $value
     * @return ProcurementOrder
     */
    public function setTotalNum($value)
    {
        $this->__set(self::TOTAL_NUM, $value);

        return $this;
    }

    /**
     * Gets 订单创建时间
     * @return string
     */
    public function getCreateTime()
    {
        return $this->__get(self::CREATE_TIME);
    }

    /**
     * Sets 订单创建时间
     * @param string $value
     * @return ProcurementOrder
     */
    public function setCreateTime($value)
    {
        $this->__set(self::CREATE_TIME, $value);

        return $this;
    }

    /**
     * Gets 交易完成时间
     * @return string
     */
    public function getFinishTime()
    {
        return $this->__get(self::FINISH_TIME);
    }

    /**
     * Sets 交易完成时间
     * @param string $value
     * @return ProcurementOrder
     */
    public function setFinishTime($value)
    {
        $this->__set(self::FINISH_TIME, $value);

        return $this;
    }

    /**
     * Gets 绑定供应商id
     * @return int
     */
    public function getBoundCommunityID()
    {
        return $this->__get(self::BOUND_COMMUNITY_ID);
    }

    /**
     * Sets 绑定供应商id
     * @param int $value
     * @return ProcurementOrder
     */
    public function setBoundCommunityID($value)
    {
        $this->__set(self::BOUND_COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 绑定供应商商城id
     * @return int
     */
    public function getBoundStoreID()
    {
        return $this->__get(self::BOUND_STORE_ID);
    }

    /**
     * Sets 绑定供应商商城id
     * @param int $value
     * @return ProcurementOrder
     */
    public function setBoundStoreID($value)
    {
        $this->__set(self::BOUND_STORE_ID, $value);

        return $this;
    }

    /**
     * Gets 商城id
     * @return int
     */
    public function getStoreID()
    {
        return $this->__get(self::STORE_ID);
    }

    /**
     * Sets 商城id
     * @param int $value
     * @return ProcurementOrder
     */
    public function setStoreID($value)
    {
        $this->__set(self::STORE_ID, $value);

        return $this;
    }

    /**
     * Gets 报价单id
     * @return int
     */
    public function getCategoryID()
    {
        return $this->__get(self::CATEGORY_ID);
    }

    /**
     * Sets 报价单id
     * @param int $value
     * @return ProcurementOrder
     */
    public function setCategoryID($value)
    {
        $this->__set(self::CATEGORY_ID, $value);

        return $this;
    }

    /**
     * Gets 退款退货原订单号
     * @return string
     */
    public function getRefundOrderID()
    {
        return $this->__get(self::REFUND_ORDER_ID);
    }

    /**
     * Sets 退款退货原订单号
     * @param string $value
     * @return ProcurementOrder
     */
    public function setRefundOrderID($value)
    {
        $this->__set(self::REFUND_ORDER_ID, $value);

        return $this;
    }

    /**
     * Gets 退款退货原因描述
     * @return string
     */
    public function getRefundDescribe()
    {
        return $this->__get(self::REFUND_DESCRIBE);
    }

    /**
     * Sets 退款退货原因描述
     * @param string $value
     * @return ProcurementOrder
     */
    public function setRefundDescribe($value)
    {
        $this->__set(self::REFUND_DESCRIBE, $value);

        return $this;
    }

    /**
     * Gets 退款退货图片地址1
     * @return string
     */
    public function getRefundImgFirst()
    {
        return $this->__get(self::REFUND_IMG_FIRST);
    }

    /**
     * Sets 退款退货图片地址1
     * @param string $value
     * @return ProcurementOrder
     */
    public function setRefundImgFirst($value)
    {
        $this->__set(self::REFUND_IMG_FIRST, $value);

        return $this;
    }

    /**
     * Gets 退款退货图片地址2
     * @return string
     */
    public function getRefundImgSecond()
    {
        return $this->__get(self::REFUND_IMG_SECOND);
    }

    /**
     * Sets 退款退货图片地址2
     * @param string $value
     * @return ProcurementOrder
     */
    public function setRefundImgSecond($value)
    {
        $this->__set(self::REFUND_IMG_SECOND, $value);

        return $this;
    }

    /**
     * Gets 退款退货图片地址3
     * @return string
     */
    public function getRefundImgThird()
    {
        return $this->__get(self::REFUND_IMG_THIRD);
    }

    /**
     * Sets 退款退货图片地址3
     * @param string $value
     * @return ProcurementOrder
     */
    public function setRefundImgThird($value)
    {
        $this->__set(self::REFUND_IMG_THIRD, $value);

        return $this;
    }

    /**
     * Gets 是否是自订
     * @return string
     */
    public function getOrderSelf()
    {
        return $this->__get(self::ORDER_SELF);
    }

    /**
     * Sets 是否是自订
     * @param string $value
     * @return ProcurementOrder
     */
    public function setOrderSelf($value)
    {
        $this->__set(self::ORDER_SELF, $value);

        return $this;
    }

    /**
     * Gets 交易状态
     * @return string
     */
    public function getStatus()
    {
        return $this->__get(self::STATUS);
    }

    /**
     * Gets 交易状态 display name
     * @return string
     */
    public function getStatus_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('status');
        return $option['enum']::getDisplayName($this->__get(self::STATUS));
    }

    /**
     * Sets 交易状态
     * @param string $value
     * @return ProcurementOrder
     */
    public function setStatus($value)
    {
        $this->__set(self::STATUS, $value);

        return $this;
    }
}
?>