<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class ProductUnitType implements ValidatorInterface
{
    const KILO = 'kilo';
    const KG = 'kg';
    const TAEL = 'tael';
    const BOTTLE = 'bottle';
    const PACKAGE = 'package';
    const BOX = 'box';
    const STRIP = 'strip';
    const PART = 'part';
    const AN = 'an';
    const BAG = 'bag';
    const BASKET = 'basket';
    const COVER = 'cover';
    const HANDFUL = 'handful';
    const POUCH = 'pouch';
    const POMEGRANATE = 'pomegranate';
    const CHUNK = 'chunk';
    const ROLL = 'roll';
    const SAMLL_BOX = 'samll_box';
    const DOUBLE = 'double';
    const BIG_BOX = 'big_box';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::KILO => _META_('mp.product_unit_type.kilo'),
                self::KG => _META_('mp.product_unit_type.kg'),
                self::TAEL => _META_('mp.product_unit_type.tael'),
                self::BOTTLE => _META_('mp.product_unit_type.bottle'),
                self::PACKAGE => _META_('mp.product_unit_type.package'),
                self::BOX => _META_('mp.product_unit_type.box'),
                self::STRIP => _META_('mp.product_unit_type.strip'),
                self::PART => _META_('mp.product_unit_type.part'),
                self::AN => _META_('mp.product_unit_type.an'),
                self::BAG => _META_('mp.product_unit_type.bag'),
                self::BASKET => _META_('mp.product_unit_type.basket'),
                self::COVER => _META_('mp.product_unit_type.cover'),
                self::HANDFUL => _META_('mp.product_unit_type.handful'),
                self::POUCH => _META_('mp.product_unit_type.pouch'),
                self::POMEGRANATE => _META_('mp.product_unit_type.pomegranate'),
                self::CHUNK => _META_('mp.product_unit_type.chunk'),
                self::ROLL => _META_('mp.product_unit_type.roll'),
                self::SAMLL_BOX => _META_('mp.product_unit_type.samll_box'),
                self::DOUBLE => _META_('mp.product_unit_type.double'),
                self::BIG_BOX => _META_('mp.product_unit_type.big_box'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::KILO;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}