<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class ProductComment extends Model
{
    const PRODUCT_COMMENT_ID = 'product_comment_id';
    const MP_USER_ID = 'mp_user_id';
    const WX_USER_ID = 'wx_user_id';
    const COMMUNITY_ID = 'community_id';
    const ORDER_ID = 'order_id';
    const NICK = 'nick';
    const HEAD_PIC = 'head_pic';
    const PRODUCT_ID = 'product_id';
    const PRODUCT_TITLE = 'product_title';
    const ORDER_FINISH_TIME = 'order_finish_time';
    const COMMENT_TIME = 'comment_time';
    const COMMENT_LEVEL = 'comment_level';
    const COMMENT = 'comment';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'product_comment',
                'product_comment_id',
                [
                    'product_comment_id' => ['name' => _META_('mp.product_comment.product_comment_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.product_comment.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'wx_user_id' => ['name' => _META_('mp.product_comment.wx_user_id'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'community_id' => ['name' => _META_('mp.product_comment.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'order_id' => ['name' => _META_('mp.product_comment.order_id'), 'type' => 'text', 'length' => 32, 'required' => true],
                    'nick' => ['name' => _META_('mp.product_comment.nick'), 'type' => 'text', 'length' => 64],
                    'head_pic' => ['name' => _META_('mp.product_comment.head_pic'), 'type' => 'url'],
                    'product_id' => ['name' => _META_('mp.product_comment.product_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'product_title' => ['name' => _META_('mp.product_comment.product_title'), 'type' => 'text', 'length' => 128, 'required' => true],
                    'order_finish_time' => ['name' => _META_('mp.product_comment.order_finish_time'), 'type' => 'datetime'],
                    'comment_time' => ['name' => _META_('mp.product_comment.comment_time'), 'type' => 'datetime'],
                    'comment_level' => ['name' => _META_('mp.product_comment.comment_level'), 'type' => 'int', 'length' => 1],
                    'comment' => ['name' => _META_('mp.product_comment.comment'), 'type' => 'text'],
                ],
                [
                    'auto_increment_id' => 'product_comment_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getProductCommentID()
    {
        return $this->__get(self::PRODUCT_COMMENT_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return ProductComment
     */
    public function setProductCommentID($value)
    {
        $this->__set(self::PRODUCT_COMMENT_ID, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return ProductComment
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets wx_user.wx_user_id
     * @return string
     */
    public function getWxUserID()
    {
        return $this->__get(self::WX_USER_ID);
    }

    /**
     * Sets wx_user.wx_user_id
     * @param string $value
     * @return ProductComment
     */
    public function setWxUserID($value)
    {
        $this->__set(self::WX_USER_ID, $value);

        return $this;
    }

    /**
     * Gets ‘community.community_id’
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets ‘community.community_id’
     * @param int $value
     * @return ProductComment
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 订单号
     * @return string
     */
    public function getOrderID()
    {
        return $this->__get(self::ORDER_ID);
    }

    /**
     * Sets 订单号
     * @param string $value
     * @return ProductComment
     */
    public function setOrderID($value)
    {
        $this->__set(self::ORDER_ID, $value);

        return $this;
    }

    /**
     * Gets 称呼
     * @return string
     */
    public function getNick()
    {
        return $this->__get(self::NICK);
    }

    /**
     * Sets 称呼
     * @param string $value
     * @return ProductComment
     */
    public function setNick($value)
    {
        $this->__set(self::NICK, $value);

        return $this;
    }

    /**
     * Gets 头像
     * @return string
     */
    public function getHeadPic()
    {
        return $this->__get(self::HEAD_PIC);
    }

    /**
     * Sets 头像
     * @param string $value
     * @return ProductComment
     */
    public function setHeadPic($value)
    {
        $this->__set(self::HEAD_PIC, $value);

        return $this;
    }

    /**
     * Gets 产品id
     * @return int
     */
    public function getProductID()
    {
        return $this->__get(self::PRODUCT_ID);
    }

    /**
     * Sets 产品id
     * @param int $value
     * @return ProductComment
     */
    public function setProductID($value)
    {
        $this->__set(self::PRODUCT_ID, $value);

        return $this;
    }

    /**
     * Gets 产品名称
     * @return string
     */
    public function getProductTitle()
    {
        return $this->__get(self::PRODUCT_TITLE);
    }

    /**
     * Sets 产品名称
     * @param string $value
     * @return ProductComment
     */
    public function setProductTitle($value)
    {
        $this->__set(self::PRODUCT_TITLE, $value);

        return $this;
    }

    /**
     * Gets 购买时间
     * @return string
     */
    public function getOrderFinishTime()
    {
        return $this->__get(self::ORDER_FINISH_TIME);
    }

    /**
     * Sets 购买时间
     * @param string $value
     * @return ProductComment
     */
    public function setOrderFinishTime($value)
    {
        $this->__set(self::ORDER_FINISH_TIME, $value);

        return $this;
    }

    /**
     * Gets 评论时间
     * @return string
     */
    public function getCommentTime()
    {
        return $this->__get(self::COMMENT_TIME);
    }

    /**
     * Sets 评论时间
     * @param string $value
     * @return ProductComment
     */
    public function setCommentTime($value)
    {
        $this->__set(self::COMMENT_TIME, $value);

        return $this;
    }

    /**
     * Gets 评论星数
     * @return int
     */
    public function getCommentLevel()
    {
        return $this->__get(self::COMMENT_LEVEL);
    }

    /**
     * Sets 评论星数
     * @param int $value
     * @return ProductComment
     */
    public function setCommentLevel($value)
    {
        $this->__set(self::COMMENT_LEVEL, $value);

        return $this;
    }

    /**
     * Gets 评论内容
     * @return string
     */
    public function getComment()
    {
        return $this->__get(self::COMMENT);
    }

    /**
     * Sets 评论内容
     * @param string $value
     * @return ProductComment
     */
    public function setComment($value)
    {
        $this->__set(self::COMMENT, $value);

        return $this;
    }
}
?>