<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class TestTest extends Model
{
    const TEST_TEST_ID = 'test_test_id';
    const POWER = 'power';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'test_test',
                'test_test_id',
                [
                    'test_test_id' => ['name' => _META_('mp.test_test.test_test_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'power' => ['name' => _META_('mp.test_test.power'), 'type' => 'text', 'max' => 32, 'enum' => new CompanyAdminPowerType(), 'db_insert' => true],
                ],
                [
                    'auto_increment_id' => 'test_test_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getTestTestID()
    {
        return $this->__get(self::TEST_TEST_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return TestTest
     */
    public function setTestTestID($value)
    {
        $this->__set(self::TEST_TEST_ID, $value);

        return $this;
    }

    /**
     * Gets power
     * @return string
     */
    public function getPower()
    {
        return $this->__get(self::POWER);
    }

    /**
     * Gets power display name
     * @return string
     */
    public function getPower_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('power');
        return $option['enum']::getDisplayName($this->__get(self::POWER));
    }

    /**
     * Sets power
     * @param string $value
     * @return TestTest
     */
    public function setPower($value)
    {
        $this->__set(self::POWER, $value);

        return $this;
    }
}
?>