<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class UserNotifySendStatus implements ValidatorInterface
{
    const SEND_NO = 'send_no';
    const SEND_WAIT = 'send_wait';
    const SEND_PROCESS = 'send_process';
    const SEND_FINISHED = 'send_finished';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::SEND_NO => _META_('mp.user_notify_send_status.send_no'),
                self::SEND_WAIT => _META_('mp.user_notify_send_status.send_wait'),
                self::SEND_PROCESS => _META_('mp.user_notify_send_status.send_process'),
                self::SEND_FINISHED => _META_('mp.user_notify_send_status.send_finished'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::SEND_NO;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}