<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class WjCustomerProfile implements ValidatorInterface
{
    const NONE = 'none';
    const REQUIRED = 'required';
    const OPTIONAL = 'optional';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::NONE => _META_('mp.wj_customer_profile.none'),
                self::REQUIRED => _META_('mp.wj_customer_profile.required'),
                self::OPTIONAL => _META_('mp.wj_customer_profile.optional'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::NONE;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}