<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class WjQuestionnaire extends Model
{
    const WJ_QUESTIONNAIRE_ID = 'wj_questionnaire_id';
    const _CREATED_AT = '_created_at';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const TITLE = 'title';
    const HEAD_DESC = 'head_desc';
    const TAIL_DESC = 'tail_desc';
    const COMMENT = 'comment';
    const CUSTOMER_PROFILE = 'customer_profile';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'wj_questionnaire',
                'wj_questionnaire_id',
                [
                    'wj_questionnaire_id' => ['name' => _META_('mp.wj_questionnaire.wj_questionnaire_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('mp.wj_questionnaire._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.wj_questionnaire.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.wj_questionnaire.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'title' => ['name' => _META_('mp.wj_questionnaire.title'), 'type' => 'text', 'length' => 255, 'required' => true],
                    'head_desc' => ['name' => _META_('mp.wj_questionnaire.head_desc'), 'type' => 'text', 'length' => 255, 'required' => true],
                    'tail_desc' => ['name' => _META_('mp.wj_questionnaire.tail_desc'), 'type' => 'text', 'length' => 255, 'required' => true],
                    'comment' => ['name' => _META_('mp.wj_questionnaire.comment'), 'type' => 'text'],
                    'customer_profile' => ['name' => _META_('mp.wj_questionnaire.customer_profile'), 'type' => 'text', 'max' => 32, 'required' => true, 'enum' => new WjCustomerProfile(), 'db_insert' => true],
                ],
                [
                    'auto_increment_id' => 'wj_questionnaire_id',
                    'create_timestamp' => '_created_at',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getWjQuestionnaireID()
    {
        return $this->__get(self::WJ_QUESTIONNAIRE_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return WjQuestionnaire
     */
    public function setWjQuestionnaireID($value)
    {
        $this->__set(self::WJ_QUESTIONNAIRE_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return WjQuestionnaire
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return WjQuestionnaire
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return WjQuestionnaire
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 问卷名称
     * @return string
     */
    public function getTitle()
    {
        return $this->__get(self::TITLE);
    }

    /**
     * Sets 问卷名称
     * @param string $value
     * @return WjQuestionnaire
     */
    public function setTitle($value)
    {
        $this->__set(self::TITLE, $value);

        return $this;
    }

    /**
     * Gets 卷首语
     * @return string
     */
    public function getHeadDesc()
    {
        return $this->__get(self::HEAD_DESC);
    }

    /**
     * Sets 卷首语
     * @param string $value
     * @return WjQuestionnaire
     */
    public function setHeadDesc($value)
    {
        $this->__set(self::HEAD_DESC, $value);

        return $this;
    }

    /**
     * Gets 卷尾语
     * @return string
     */
    public function getTailDesc()
    {
        return $this->__get(self::TAIL_DESC);
    }

    /**
     * Sets 卷尾语
     * @param string $value
     * @return WjQuestionnaire
     */
    public function setTailDesc($value)
    {
        $this->__set(self::TAIL_DESC, $value);

        return $this;
    }

    /**
     * Gets 问卷描述
     * @return string
     */
    public function getComment()
    {
        return $this->__get(self::COMMENT);
    }

    /**
     * Sets 问卷描述
     * @param string $value
     * @return WjQuestionnaire
     */
    public function setComment($value)
    {
        $this->__set(self::COMMENT, $value);

        return $this;
    }

    /**
     * Gets 用户个人信息
     * @return string
     */
    public function getCustomerProfile()
    {
        return $this->__get(self::CUSTOMER_PROFILE);
    }

    /**
     * Gets 用户个人信息 display name
     * @return string
     */
    public function getCustomerProfile_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('customer_profile');
        return $option['enum']::getDisplayName($this->__get(self::CUSTOMER_PROFILE));
    }

    /**
     * Sets 用户个人信息
     * @param string $value
     * @return WjQuestionnaire
     */
    public function setCustomerProfile($value)
    {
        $this->__set(self::CUSTOMER_PROFILE, $value);

        return $this;
    }
}
?>