<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class WjQuestion extends Model
{
    const WJ_QUESTION_ID = 'wj_question_id';
    const _CREATED_AT = '_created_at';
    const MP_USER_ID = 'mp_user_id';
    const COMMUNITY_ID = 'community_id';
    const WJ_QUESTIONNAIRE_ID = 'wj_questionnaire_id';
    const CONTENT = 'content';
    const COMMENT = 'comment';
    const SORT_NO = 'sort_no';
    const PLACEHOLDER = 'placeholder';
    const QUESTION_TYPE = 'question_type';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'wj_question',
                'wj_question_id',
                [
                    'wj_question_id' => ['name' => _META_('mp.wj_question.wj_question_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    '_created_at' => ['name' => _META_('mp.wj_question._created_at'), 'type' => 'timestamp', 'required' => true, 'default' => new DbExpr('NOW()'), 'roc' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.wj_question.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'community_id' => ['name' => _META_('mp.wj_question.community_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'wj_questionnaire_id' => ['name' => _META_('mp.wj_question.wj_questionnaire_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'content' => ['name' => _META_('mp.wj_question.content'), 'type' => 'text', 'required' => true],
                    'comment' => ['name' => _META_('mp.wj_question.comment'), 'type' => 'text'],
                    'sort_no' => ['name' => _META_('mp.wj_question.sort_no'), 'type' => 'float', 'db_insert' => true, 'required' => true],
                    'placeholder' => ['name' => _META_('mp.wj_question.placeholder'), 'type' => 'text', 'length' => 128],
                    'question_type' => ['name' => _META_('mp.wj_question.question_type'), 'type' => 'text', 'max' => 32, 'required' => true, 'enum' => new WjQuestionType(), 'db_insert' => true],
                ],
                [
                    'auto_increment_id' => 'wj_question_id',
                    'create_timestamp' => '_created_at',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getWjQuestionID()
    {
        return $this->__get(self::WJ_QUESTION_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return WjQuestion
     */
    public function setWjQuestionID($value)
    {
        $this->__set(self::WJ_QUESTION_ID, $value);

        return $this;
    }

    /**
     * Gets createdat
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->__get(self::_CREATED_AT);
    }

    /**
     * Sets createdat
     * @param string $value
     * @return WjQuestion
     */
    public function setCreatedAt($value)
    {
        $this->__set(self::_CREATED_AT, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return WjQuestion
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCommunityID()
    {
        return $this->__get(self::COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return WjQuestion
     */
    public function setCommunityID($value)
    {
        $this->__set(self::COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets wj_questionnaire.wj_questionnaire_id
     * @return int
     */
    public function getWjQuestionnaireID()
    {
        return $this->__get(self::WJ_QUESTIONNAIRE_ID);
    }

    /**
     * Sets wj_questionnaire.wj_questionnaire_id
     * @param int $value
     * @return WjQuestion
     */
    public function setWjQuestionnaireID($value)
    {
        $this->__set(self::WJ_QUESTIONNAIRE_ID, $value);

        return $this;
    }

    /**
     * Gets 问题内容
     * @return string
     */
    public function getContent()
    {
        return $this->__get(self::CONTENT);
    }

    /**
     * Sets 问题内容
     * @param string $value
     * @return WjQuestion
     */
    public function setContent($value)
    {
        $this->__set(self::CONTENT, $value);

        return $this;
    }

    /**
     * Gets 问题描述
     * @return string
     */
    public function getComment()
    {
        return $this->__get(self::COMMENT);
    }

    /**
     * Sets 问题描述
     * @param string $value
     * @return WjQuestion
     */
    public function setComment($value)
    {
        $this->__set(self::COMMENT, $value);

        return $this;
    }

    /**
     * Gets 排序
     * @return float
     */
    public function getSortNo()
    {
        return $this->__get(self::SORT_NO);
    }

    /**
     * Sets 排序
     * @param float $value
     * @return WjQuestion
     */
    public function setSortNo($value)
    {
        $this->__set(self::SORT_NO, $value);

        return $this;
    }

    /**
     * Gets 输入框提示语
     * @return string
     */
    public function getPlaceholder()
    {
        return $this->__get(self::PLACEHOLDER);
    }

    /**
     * Sets 输入框提示语
     * @param string $value
     * @return WjQuestion
     */
    public function setPlaceholder($value)
    {
        $this->__set(self::PLACEHOLDER, $value);

        return $this;
    }

    /**
     * Gets 问题类型
     * @return string
     */
    public function getQuestionType()
    {
        return $this->__get(self::QUESTION_TYPE);
    }

    /**
     * Gets 问题类型 display name
     * @return string
     */
    public function getQuestionType_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('question_type');
        return $option['enum']::getDisplayName($this->__get(self::QUESTION_TYPE));
    }

    /**
     * Sets 问题类型
     * @param string $value
     * @return WjQuestion
     */
    public function setQuestionType($value)
    {
        $this->__set(self::QUESTION_TYPE, $value);

        return $this;
    }
}
?>