<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class WjQuestionType implements ValidatorInterface
{
    const CHOICE_SINGLE = 'choice_single';
    const CHOICE_MULTIPLE = 'choice_multiple';
    const INPUT_SINGLE = 'input_single';
    const INPUT_MULTIPLE = 'input_multiple';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::CHOICE_SINGLE => _META_('mp.wj_question_type.choice_single'),
                self::CHOICE_MULTIPLE => _META_('mp.wj_question_type.choice_multiple'),
                self::INPUT_SINGLE => _META_('mp.wj_question_type.input_single'),
                self::INPUT_MULTIPLE => _META_('mp.wj_question_type.input_multiple'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::CHOICE_SINGLE;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}