<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class WxNavigationType implements ValidatorInterface
{
    const GENERAL = 'general';
    const ADMIN = 'admin';
    const ORDER_TAKE_AWAY = 'order_take_away';
    const BROWSE_MENU = 'browse_menu';
    const COMMENT_ORDER = 'comment_order';
    const PROFILE = 'profile';
    const AWARD_RECORD = 'award_record';
    const FEEDBACK = 'feedback';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::GENERAL => _META_('mp.wx_navigation_type.general'),
                self::ADMIN => _META_('mp.wx_navigation_type.admin'),
                self::ORDER_TAKE_AWAY => _META_('mp.wx_navigation_type.order_take_away'),
                self::BROWSE_MENU => _META_('mp.wx_navigation_type.browse_menu'),
                self::COMMENT_ORDER => _META_('mp.wx_navigation_type.comment_order'),
                self::PROFILE => _META_('mp.wx_navigation_type.profile'),
                self::AWARD_RECORD => _META_('mp.wx_navigation_type.award_record'),
                self::FEEDBACK => _META_('mp.wx_navigation_type.feedback'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::GENERAL;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}