<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class WxSubMenu extends Model
{
    const WX_SUB_MENU_ID = 'wx_sub_menu_id';
    const MP_USER_ID = 'mp_user_id';
    const WX_MENU_ID = 'wx_menu_id';
    const WX_MENU_NAME = 'wx_menu_name';
    const WX_MENU_KEY = 'wx_menu_key';
    const SORT_NO = 'sort_no';
    const CONTENT_VALUE = 'content_value';
    const URL = 'url';
    const ACCESS_AUTHORITY = 'access_authority';
    const WX_MENU_TYPE = 'wx_menu_type';
    const CONTENT_TYPE = 'content_type';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'wx_sub_menu',
                'wx_sub_menu_id',
                [
                    'wx_sub_menu_id' => ['name' => _META_('mp.wx_sub_menu.wx_sub_menu_id'), 'type' => 'int', 'length' => 10, 'min' => 1, 'required' => true, 'db_insert' => true, 'rou' => true],
                    'mp_user_id' => ['name' => _META_('mp.wx_sub_menu.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'wx_menu_id' => ['name' => _META_('mp.wx_sub_menu.wx_menu_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'wx_menu_name' => ['name' => _META_('mp.wx_sub_menu.wx_menu_name'), 'type' => 'text', 'length' => 16, 'required' => true],
                    'wx_menu_key' => ['name' => _META_('mp.wx_sub_menu.wx_menu_key'), 'type' => 'text', 'length' => 32],
                    'sort_no' => ['name' => _META_('mp.wx_sub_menu.sort_no'), 'type' => 'float', 'db_insert' => true, 'required' => true],
                    'content_value' => ['name' => _META_('mp.wx_sub_menu.content_value'), 'type' => 'text'],
                    'url' => ['name' => _META_('mp.wx_sub_menu.url'), 'type' => 'url'],
                    'access_authority' => ['name' => _META_('mp.wx_sub_menu.access_authority'), 'type' => 'text', 'max' => 32, 'db_insert' => true, 'enum' => new AccessAuthorityType()],
                    'wx_menu_type' => ['name' => _META_('mp.wx_sub_menu.wx_menu_type'), 'type' => 'text', 'max' => 32, 'required' => true, 'db_insert' => true, 'enum' => new WxMenuType()],
                    'content_type' => ['name' => _META_('mp.wx_sub_menu.content_type'), 'type' => 'text', 'max' => 32, 'enum' => new WxMenuContentType(), 'db_insert' => true],
                ],
                [
                    'auto_increment_id' => 'wx_sub_menu_id',
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets id
     * @return int
     */
    public function getWxSubMenuID()
    {
        return $this->__get(self::WX_SUB_MENU_ID);
    }

    /**
     * Sets id
     * @param int $value
     * @return WxSubMenu
     */
    public function setWxSubMenuID($value)
    {
        $this->__set(self::WX_SUB_MENU_ID, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return WxSubMenu
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets 微信子菜单id
     * @return int
     */
    public function getWxMenuID()
    {
        return $this->__get(self::WX_MENU_ID);
    }

    /**
     * Sets 微信子菜单id
     * @param int $value
     * @return WxSubMenu
     */
    public function setWxMenuID($value)
    {
        $this->__set(self::WX_MENU_ID, $value);

        return $this;
    }

    /**
     * Gets 菜单名字
     * @return string
     */
    public function getWxMenuName()
    {
        return $this->__get(self::WX_MENU_NAME);
    }

    /**
     * Sets 菜单名字
     * @param string $value
     * @return WxSubMenu
     */
    public function setWxMenuName($value)
    {
        $this->__set(self::WX_MENU_NAME, $value);

        return $this;
    }

    /**
     * Gets 按钮key值
     * @return string
     */
    public function getWxMenuKey()
    {
        return $this->__get(self::WX_MENU_KEY);
    }

    /**
     * Sets 按钮key值
     * @param string $value
     * @return WxSubMenu
     */
    public function setWxMenuKey($value)
    {
        $this->__set(self::WX_MENU_KEY, $value);

        return $this;
    }

    /**
     * Gets 排序id
     * @return float
     */
    public function getSortNo()
    {
        return $this->__get(self::SORT_NO);
    }

    /**
     * Sets 排序id
     * @param float $value
     * @return WxSubMenu
     */
    public function setSortNo($value)
    {
        $this->__set(self::SORT_NO, $value);

        return $this;
    }

    /**
     * Gets 导航内容
     * @return string
     */
    public function getContentValue()
    {
        return $this->__get(self::CONTENT_VALUE);
    }

    /**
     * Sets 导航内容
     * @param string $value
     * @return WxSubMenu
     */
    public function setContentValue($value)
    {
        $this->__set(self::CONTENT_VALUE, $value);

        return $this;
    }

    /**
     * Gets view类型所对应的网址
     * @return string
     */
    public function getUrl()
    {
        return $this->__get(self::URL);
    }

    /**
     * Sets view类型所对应的网址
     * @param string $value
     * @return WxSubMenu
     */
    public function setUrl($value)
    {
        $this->__set(self::URL, $value);

        return $this;
    }

    /**
     * Gets 访问权限类型
     * @return string
     */
    public function getAccessAuthority()
    {
        return $this->__get(self::ACCESS_AUTHORITY);
    }

    /**
     * Gets 访问权限类型 display name
     * @return string
     */
    public function getAccessAuthority_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('access_authority');
        return $option['enum']::getDisplayName($this->__get(self::ACCESS_AUTHORITY));
    }

    /**
     * Sets 访问权限类型
     * @param string $value
     * @return WxSubMenu
     */
    public function setAccessAuthority($value)
    {
        $this->__set(self::ACCESS_AUTHORITY, $value);

        return $this;
    }

    /**
     * Gets 微信菜单类型
     * @return string
     */
    public function getWxMenuType()
    {
        return $this->__get(self::WX_MENU_TYPE);
    }

    /**
     * Gets 微信菜单类型 display name
     * @return string
     */
    public function getWxMenuType_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('wx_menu_type');
        return $option['enum']::getDisplayName($this->__get(self::WX_MENU_TYPE));
    }

    /**
     * Sets 微信菜单类型
     * @param string $value
     * @return WxSubMenu
     */
    public function setWxMenuType($value)
    {
        $this->__set(self::WX_MENU_TYPE, $value);

        return $this;
    }

    /**
     * Gets 微信菜单内容类型
     * @return string
     */
    public function getContentType()
    {
        return $this->__get(self::CONTENT_TYPE);
    }

    /**
     * Gets 微信菜单内容类型 display name
     * @return string
     */
    public function getContentType_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('content_type');
        return $option['enum']::getDisplayName($this->__get(self::CONTENT_TYPE));
    }

    /**
     * Sets 微信菜单内容类型
     * @param string $value
     * @return WxSubMenu
     */
    public function setContentType($value)
    {
        $this->__set(self::CONTENT_TYPE, $value);

        return $this;
    }
}
?>