<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace MP\Model\Mp;

use Bluefin\Convention;
use Bluefin\Data\ValidatorInterface;

class WxUserLevel implements ValidatorInterface
{
    const LEVEL_0 = 'level_0';
    const LEVEL_1 = 'level_1';
    const LEVEL_2 = 'level_2';
    const LEVEL_3 = 'level_3';
    const LEVEL_4 = 'level_4';

    private static $_data;

    public static function getDictionary()
    {
        if (!isset(self::$_data))
        {
            self::$_data = array(
                self::LEVEL_0 => _META_('mp.wx_user_level.level_0'),
                self::LEVEL_1 => _META_('mp.wx_user_level.level_1'),
                self::LEVEL_2 => _META_('mp.wx_user_level.level_2'),
                self::LEVEL_3 => _META_('mp.wx_user_level.level_3'),
                self::LEVEL_4 => _META_('mp.wx_user_level.level_4'),
            );
        }

        return self::$_data;
    }

    public static function getValues()
    {
        $data = self::getDictionary();
        return array_keys($data);
    }

    public static function getDisplayName($value)
    {
        $data = self::getDictionary();
        return $data[$value];
    }

    public static function getDefaultValue()
    {
        return self::LEVEL_0;
    }

    public function validate($value)
    {
        $data = self::getDictionary();
        return array_key_exists($value, $data);
    }
}