<?php
//Don't edit this file which is generated by Bluefin Lance.
//You can put custom business logic into a Business class under MP\Business namespace.
namespace MP\Model\Mp;

use Bluefin\App;
use Bluefin\Convention;
use Bluefin\VarText;
use Bluefin\Data\Type;
use Bluefin\Data\Model;
use Bluefin\Data\Database;
use Bluefin\Data\ModelMetadata;
use Bluefin\Data\DbExpr;

class WxUser extends Model
{
    const CREATE_TIME = 'create_time';
    const WX_USER_ID = 'wx_user_id';
    const MP_USER_ID = 'mp_user_id';
    const VIP_NO = 'vip_no';
    const PHONE = 'phone';
    const IS_FANS = 'is_fans';
    const IS_ADMIN = 'is_admin';
    const NICK = 'nick';
    const NAME = 'name';
    const LAST_ACCESS_YMD = 'last_access_ymd';
    const COMMENT = 'comment';
    const IDIOGRAPH = 'idiograph';
    const ADDRESS = 'address';
    const BIRTH = 'birth';
    const GENDER = 'gender';
    const HEAD_PIC = 'head_pic';
    const MESSAGE_DATE = 'message_date';
    const CARD_ID = 'card_id';
    const EMAIL = 'email';
    const CURRENT_COMMUNITY_ID = 'current_community_id';
    const LATITUDEUSER = 'latitudeUser';
    const LONGITUDEUSER = 'longitudeUser';
    const W_PROVINCE = 'w_province';
    const W_CITY = 'w_city';
    const REGISTER_TIME = 'register_time';
    const IDENTIFY_TIME = 'identify_time';
    const LAST_ACCESS = 'last_access';
    const IS_QUIT = 'is_quit';
    const USER_LEVEL = 'user_level';



    protected static $__metadata;

    /**
     * @static
     * @return \Bluefin\Data\ModelMetadata
     */
    public static function s_metadata()
    {
        if (!isset(self::$__metadata))
        {
            self::$__metadata = new ModelMetadata(
                'mp',
                'wx_user',
                'wx_user_id',
                [
                    'create_time' => ['name' => _META_('mp.wx_user.create_time'), 'type' => 'datetime', 'required' => true],
                    'wx_user_id' => ['name' => _META_('mp.wx_user.wx_user_id'), 'type' => 'text', 'length' => 64, 'required' => true],
                    'mp_user_id' => ['name' => _META_('mp.wx_user.mp_user_id'), 'type' => 'int', 'length' => 10, 'required' => true],
                    'vip_no' => ['name' => _META_('mp.wx_user.vip_no'), 'type' => 'int', 'length' => 20, 'db_insert' => true, 'required' => true],
                    'phone' => ['name' => _META_('mp.wx_user.phone'), 'type' => 'text', 'length' => 32],
                    'is_fans' => ['name' => _META_('mp.wx_user.is_fans'), 'type' => 'int', 'length' => 1, 'db_insert' => true, 'required' => true],
                    'is_admin' => ['name' => _META_('mp.wx_user.is_admin'), 'type' => 'int', 'length' => 1, 'db_insert' => true, 'required' => true],
                    'nick' => ['name' => _META_('mp.wx_user.nick'), 'type' => 'text', 'length' => 64],
                    'name' => ['name' => _META_('mp.wx_user.name'), 'type' => 'text', 'length' => 64],
                    'last_access_ymd' => ['name' => _META_('mp.wx_user.last_access_ymd'), 'type' => 'int', 'length' => 10, 'db_insert' => true, 'required' => true],
                    'comment' => ['name' => _META_('mp.wx_user.comment'), 'type' => 'text', 'length' => 128],
                    'idiograph' => ['name' => _META_('mp.wx_user.idiograph'), 'type' => 'text', 'length' => 255],
                    'address' => ['name' => _META_('mp.wx_user.address'), 'type' => 'text', 'length' => 255],
                    'birth' => ['name' => _META_('mp.wx_user.birth'), 'type' => 'int', 'length' => 10],
                    'gender' => ['name' => _META_('mp.wx_user.gender'), 'type' => 'text', 'length' => 6],
                    'head_pic' => ['name' => _META_('mp.wx_user.head_pic'), 'type' => 'url'],
                    'message_date' => ['name' => _META_('mp.wx_user.message_date'), 'type' => 'text', 'length' => 16, 'db_insert' => true],
                    'card_id' => ['name' => _META_('mp.wx_user.card_id'), 'type' => 'text', 'length' => 255],
                    'email' => ['name' => _META_('mp.wx_user.email'), 'type' => 'text', 'length' => 255],
                    'current_community_id' => ['name' => _META_('mp.wx_user.current_community_id'), 'type' => 'int', 'length' => 10, 'db_insert' => true, 'required' => true],
                    'latitudeUser' => ['name' => _META_('mp.wx_user.latitudeUser'), 'type' => 'text', 'length' => 255],
                    'longitudeUser' => ['name' => _META_('mp.wx_user.longitudeUser'), 'type' => 'text', 'length' => 255],
                    'w_province' => ['name' => _META_('mp.wx_user.w_province'), 'type' => 'text', 'length' => 255],
                    'w_city' => ['name' => _META_('mp.wx_user.w_city'), 'type' => 'text', 'length' => 255],
                    'register_time' => ['name' => _META_('mp.wx_user.register_time'), 'type' => 'datetime'],
                    'identify_time' => ['name' => _META_('mp.wx_user.identify_time'), 'type' => 'datetime'],
                    'last_access' => ['name' => _META_('mp.wx_user.last_access'), 'type' => 'datetime'],
                    'is_quit' => ['name' => _META_('mp.wx_user.is_quit'), 'type' => 'bool', 'db_insert' => true],
                    'user_level' => ['name' => _META_('mp.wx_user.user_level'), 'type' => 'text', 'max' => 32, 'required' => true, 'enum' => new WxUserLevel(), 'db_insert' => true],
                ],
                [
                    'unique_keys' => [['mp_user_id', 'vip_no']],
                ],
                [
                ],
                [
                ],
                [
                    Model::OP_CREATE => NULL,
                    Model::OP_GET => NULL,
                    Model::OP_UPDATE => NULL,
                    Model::OP_DELETE => NULL,
                ]
            );
        }

        return self::$__metadata;
    }

    public function __construct($condition = null)
    {
        parent::__construct(self::s_metadata());

        if (isset($condition))
        {
            $this->load($condition);
        }
        else
        {
            $this->reset();
        }
    }

    /**
     * Gets 创建时间
     * @return string
     */
    public function getCreateTime()
    {
        return $this->__get(self::CREATE_TIME);
    }

    /**
     * Sets 创建时间
     * @param string $value
     * @return WxUser
     */
    public function setCreateTime($value)
    {
        $this->__set(self::CREATE_TIME, $value);

        return $this;
    }

    /**
     * Gets 微信用户openid
     * @return string
     */
    public function getWxUserID()
    {
        return $this->__get(self::WX_USER_ID);
    }

    /**
     * Sets 微信用户openid
     * @param string $value
     * @return WxUser
     */
    public function setWxUserID($value)
    {
        $this->__set(self::WX_USER_ID, $value);

        return $this;
    }

    /**
     * Gets mp_user.mp_user_id
     * @return int
     */
    public function getMpUserID()
    {
        return $this->__get(self::MP_USER_ID);
    }

    /**
     * Sets mp_user.mp_user_id
     * @param int $value
     * @return WxUser
     */
    public function setMpUserID($value)
    {
        $this->__set(self::MP_USER_ID, $value);

        return $this;
    }

    /**
     * Gets 会员号
     * @return int
     */
    public function getVipNo()
    {
        return $this->__get(self::VIP_NO);
    }

    /**
     * Sets 会员号
     * @param int $value
     * @return WxUser
     */
    public function setVipNo($value)
    {
        $this->__set(self::VIP_NO, $value);

        return $this;
    }

    /**
     * Gets 用户电话
     * @return string
     */
    public function getPhone()
    {
        return $this->__get(self::PHONE);
    }

    /**
     * Sets 用户电话
     * @param string $value
     * @return WxUser
     */
    public function setPhone($value)
    {
        $this->__set(self::PHONE, $value);

        return $this;
    }

    /**
     * Gets 是否是粉丝
     * @return int
     */
    public function getIsFans()
    {
        return $this->__get(self::IS_FANS);
    }

    /**
     * Sets 是否是粉丝
     * @param int $value
     * @return WxUser
     */
    public function setIsFans($value)
    {
        $this->__set(self::IS_FANS, $value);

        return $this;
    }

    /**
     * Gets 是否是管理员
     * @return int
     */
    public function getIsAdmin()
    {
        return $this->__get(self::IS_ADMIN);
    }

    /**
     * Sets 是否是管理员
     * @param int $value
     * @return WxUser
     */
    public function setIsAdmin($value)
    {
        $this->__set(self::IS_ADMIN, $value);

        return $this;
    }

    /**
     * Gets 称呼
     * @return string
     */
    public function getNick()
    {
        return $this->__get(self::NICK);
    }

    /**
     * Sets 称呼
     * @param string $value
     * @return WxUser
     */
    public function setNick($value)
    {
        $this->__set(self::NICK, $value);

        return $this;
    }

    /**
     * Gets 姓名
     * @return string
     */
    public function getName()
    {
        return $this->__get(self::NAME);
    }

    /**
     * Sets 姓名
     * @param string $value
     * @return WxUser
     */
    public function setName($value)
    {
        $this->__set(self::NAME, $value);

        return $this;
    }

    /**
     * Gets 上次访问日期
     * @return int
     */
    public function getLastAccessYmd()
    {
        return $this->__get(self::LAST_ACCESS_YMD);
    }

    /**
     * Sets 上次访问日期
     * @param int $value
     * @return WxUser
     */
    public function setLastAccessYmd($value)
    {
        $this->__set(self::LAST_ACCESS_YMD, $value);

        return $this;
    }

    /**
     * Gets 备注
     * @return string
     */
    public function getComment()
    {
        return $this->__get(self::COMMENT);
    }

    /**
     * Sets 备注
     * @param string $value
     * @return WxUser
     */
    public function setComment($value)
    {
        $this->__set(self::COMMENT, $value);

        return $this;
    }

    /**
     * Gets 个人签名
     * @return string
     */
    public function getIdiograph()
    {
        return $this->__get(self::IDIOGRAPH);
    }

    /**
     * Sets 个人签名
     * @param string $value
     * @return WxUser
     */
    public function setIdiograph($value)
    {
        $this->__set(self::IDIOGRAPH, $value);

        return $this;
    }

    /**
     * Gets 地址
     * @return string
     */
    public function getAddress()
    {
        return $this->__get(self::ADDRESS);
    }

    /**
     * Sets 地址
     * @param string $value
     * @return WxUser
     */
    public function setAddress($value)
    {
        $this->__set(self::ADDRESS, $value);

        return $this;
    }

    /**
     * Gets 生日
     * @return int
     */
    public function getBirth()
    {
        return $this->__get(self::BIRTH);
    }

    /**
     * Sets 生日
     * @param int $value
     * @return WxUser
     */
    public function setBirth($value)
    {
        $this->__set(self::BIRTH, $value);

        return $this;
    }

    /**
     * Gets 性别
     * @return string
     */
    public function getGender()
    {
        return $this->__get(self::GENDER);
    }

    /**
     * Sets 性别
     * @param string $value
     * @return WxUser
     */
    public function setGender($value)
    {
        $this->__set(self::GENDER, $value);

        return $this;
    }

    /**
     * Gets 头像
     * @return string
     */
    public function getHeadPic()
    {
        return $this->__get(self::HEAD_PIC);
    }

    /**
     * Sets 头像
     * @param string $value
     * @return WxUser
     */
    public function setHeadPic($value)
    {
        $this->__set(self::HEAD_PIC, $value);

        return $this;
    }

    /**
     * Gets 消息日期
     * @return string
     */
    public function getMessageDate()
    {
        return $this->__get(self::MESSAGE_DATE);
    }

    /**
     * Sets 消息日期
     * @param string $value
     * @return WxUser
     */
    public function setMessageDate($value)
    {
        $this->__set(self::MESSAGE_DATE, $value);

        return $this;
    }

    /**
     * Gets 卡号
     * @return string
     */
    public function getCardID()
    {
        return $this->__get(self::CARD_ID);
    }

    /**
     * Sets 卡号
     * @param string $value
     * @return WxUser
     */
    public function setCardID($value)
    {
        $this->__set(self::CARD_ID, $value);

        return $this;
    }

    /**
     * Gets 邮箱地址
     * @return string
     */
    public function getEmail()
    {
        return $this->__get(self::EMAIL);
    }

    /**
     * Sets 邮箱地址
     * @param string $value
     * @return WxUser
     */
    public function setEmail($value)
    {
        $this->__set(self::EMAIL, $value);

        return $this;
    }

    /**
     * Gets community.community_id
     * @return int
     */
    public function getCurrentCommunityID()
    {
        return $this->__get(self::CURRENT_COMMUNITY_ID);
    }

    /**
     * Sets community.community_id
     * @param int $value
     * @return WxUser
     */
    public function setCurrentCommunityID($value)
    {
        $this->__set(self::CURRENT_COMMUNITY_ID, $value);

        return $this;
    }

    /**
     * Gets 纬度
     * @return string
     */
    public function getLatitudeuser()
    {
        return $this->__get(self::LATITUDEUSER);
    }

    /**
     * Sets 纬度
     * @param string $value
     * @return WxUser
     */
    public function setLatitudeuser($value)
    {
        $this->__set(self::LATITUDEUSER, $value);

        return $this;
    }

    /**
     * Gets 经度
     * @return string
     */
    public function getLongitudeuser()
    {
        return $this->__get(self::LONGITUDEUSER);
    }

    /**
     * Sets 经度
     * @param string $value
     * @return WxUser
     */
    public function setLongitudeuser($value)
    {
        $this->__set(self::LONGITUDEUSER, $value);

        return $this;
    }

    /**
     * Gets 关注所在省/市
     * @return string
     */
    public function getWProvince()
    {
        return $this->__get(self::W_PROVINCE);
    }

    /**
     * Sets 关注所在省/市
     * @param string $value
     * @return WxUser
     */
    public function setWProvince($value)
    {
        $this->__set(self::W_PROVINCE, $value);

        return $this;
    }

    /**
     * Gets 关注所在市/区
     * @return string
     */
    public function getWCity()
    {
        return $this->__get(self::W_CITY);
    }

    /**
     * Sets 关注所在市/区
     * @param string $value
     * @return WxUser
     */
    public function setWCity($value)
    {
        $this->__set(self::W_CITY, $value);

        return $this;
    }

    /**
     * Gets 注册时间
     * @return string
     */
    public function getRegisterTime()
    {
        return $this->__get(self::REGISTER_TIME);
    }

    /**
     * Sets 注册时间
     * @param string $value
     * @return WxUser
     */
    public function setRegisterTime($value)
    {
        $this->__set(self::REGISTER_TIME, $value);

        return $this;
    }

    /**
     * Gets 认证时间
     * @return string
     */
    public function getIdentifyTime()
    {
        return $this->__get(self::IDENTIFY_TIME);
    }

    /**
     * Sets 认证时间
     * @param string $value
     * @return WxUser
     */
    public function setIdentifyTime($value)
    {
        $this->__set(self::IDENTIFY_TIME, $value);

        return $this;
    }

    /**
     * Gets 上次访问时间
     * @return string
     */
    public function getLastAccess()
    {
        return $this->__get(self::LAST_ACCESS);
    }

    /**
     * Sets 上次访问时间
     * @param string $value
     * @return WxUser
     */
    public function setLastAccess($value)
    {
        $this->__set(self::LAST_ACCESS, $value);

        return $this;
    }

    /**
     * Gets 是否退出
     * @return bool
     */
    public function getIsQuit()
    {
        return $this->__get(self::IS_QUIT);
    }

    /**
     * Sets 是否退出
     * @param bool $value
     * @return WxUser
     */
    public function setIsQuit($value)
    {
        $this->__set(self::IS_QUIT, $value);

        return $this;
    }

    /**
     * Gets 用户等级
     * @return string
     */
    public function getUserLevel()
    {
        return $this->__get(self::USER_LEVEL);
    }

    /**
     * Gets 用户等级 display name
     * @return string
     */
    public function getUserLevel_EnumValue()
    {
        $option = $this->metadata()->getFilterOption('user_level');
        return $option['enum']::getDisplayName($this->__get(self::USER_LEVEL));
    }

    /**
     * Sets 用户等级
     * @param string $value
     * @return WxUser
     */
    public function setUserLevel($value)
    {
        $this->__set(self::USER_LEVEL, $value);

        return $this;
    }
}
?>