<?php
//Don't edit this file which is generated by Bluefin Lance.
namespace WBT\Model;

use Bluefin\Data\Database;

class WeibotuiDatabase extends Database
{
    public function __construct(array $config)
    {
        parent::__construct(
            'WBT',
            'weibotui',
            array(
                'oauth_token' => '\\WBT\\Model\\Weibotui\\OAuthToken',
                'oauth_client' => '\\WBT\\Model\\Weibotui\\OAuthClient',
                'user' => '\\WBT\\Model\\Weibotui\\User',
                'oauth_code' => '\\WBT\\Model\\Weibotui\\OAuthCode',
                'personal_profile' => '\\WBT\\Model\\Weibotui\\PersonalProfile',
                'country' => '\\WBT\\Model\\Weibotui\\Country',
                'province' => '\\WBT\\Model\\Weibotui\\Province',
                'city' => '\\WBT\\Model\\Weibotui\\City',
                'district' => '\\WBT\\Model\\Weibotui\\District',
                'address' => '\\WBT\\Model\\Weibotui\\Address',
                'user_login_record' => '\\WBT\\Model\\Weibotui\\UserLoginRecord',
                'system_property' => '\\WBT\\Model\\Weibotui\\SystemProperty',
            ),
            new \Bluefin\Data\Db\MySQL($config)
        );
    }
}