-- TABLE mp_user

CREATE TABLE IF NOT EXISTS `mp_user` (
    `_created_at` TIMESTAMP NOT NULL DEFAULT 0 COMMENT 'CreatedAt',
    `_updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UpdatedAt',
    `mp_user_id` INT(10) NOT NULL COMMENT 'mp_user_id',
    `mp_name` CHAR(64) NOT NULL COMMENT '公众账号名称',
    `followed_content` TEXT COMMENT '欢迎语',
    `comment` TEXT COMMENT '备注',
    `valid` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效',
    `api_id` CHAR(16) NOT NULL COMMENT 'ApiID',
    `token` CHAR(32) NOT NULL COMMENT 'apitoken',
    `location_x` CHAR(16) COMMENT '经度',
    `location_y` CHAR(16) COMMENT '纬度',
    `max_vip_no` INT(10) NOT NULL DEFAULT 100 COMMENT '最大会员编号',
    `phone_no` CHAR(64) COMMENT '电话号码',
    `app_id` CHAR(64) COMMENT '微信AppId',
    `app_secret` CHAR(64) COMMENT '微信AppSecret',
    `partner_id` CHAR(16) COMMENT '微信支付partnerid',
    `partner_key` CHAR(32) COMMENT '微信支付partnerkey',
    `pay_sign_key` VARCHAR(128) COMMENT '微信支付paysignkey',
    `mchid` CHAR(16) COMMENT '受理商ID',
    `pay_key` CHAR(64) COMMENT '商户支付密钥Key',
    `js_api_call_url` VARCHAR(1024) COMMENT 'jsapi跳转支付页面url',
    `sslcert_path` VARCHAR(512) COMMENT 'apiclient_cert证书路径',
    `sslkey_path` VARCHAR(512) COMMENT 'apiclient_key证书路径',
    `notify_url` VARCHAR(1024) COMMENT '异步通知url',
    `curl_timeout` INT(10) DEFAULT 30 COMMENT '请求最短时间',
    `card_logo` VARCHAR(1024) COMMENT '会员卡logo',
    `share_pic` VARCHAR(1024) COMMENT '分享文章时使用的图片',
    `card_background` VARCHAR(1024) COMMENT '会员卡背景',
    `card_list_directory` INT(10) COMMENT '会员卡页目录ID',
    `open_date` CHAR(64) COMMENT '服务开通日期',
    `send_report` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否发送报表',
    `cs_visible` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '个人设置页面显示客服专员',
    `sale_list_name` CHAR(64) COMMENT '出库销售单标题',
    `access_token` VARCHAR(512) COMMENT '公众号全局唯一票据',
    `access_token_update_time` INT(10) COMMENT '票据更新时间',
    `mp_user_type` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否是服务号',
    `order_notify_music` VARCHAR(1024) COMMENT '订单通知音乐',
    `industry` CHAR(32) DEFAULT 'internet' COMMENT '公众账号行业类型',
    PRIMARY KEY (`mp_user_id`),
    UNIQUE KEY `uk_mp_user_api_id` (`api_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='微信公众帐号';