-- TABLE wx_user

CREATE TABLE IF NOT EXISTS `wx_user` (
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `wx_user_id` CHAR(64) NOT NULL COMMENT '微信用户OpenID',
    `mp_user_id` INT(10) NOT NULL COMMENT 'mp_user.mp_user_id',
    `vip_no` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '会员号',
    `phone` CHAR(32) COMMENT '用户电话',
    `is_fans` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否是粉丝',
    `is_admin` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否是管理员',
    `nick` CHAR(64) COMMENT '称呼',
    `name` CHAR(64) COMMENT '姓名',
    `last_access_ymd` INT(10) NOT NULL DEFAULT 0 COMMENT '上次访问日期',
    `comment` VARCHAR(128) COMMENT '备注',
    `idiograph` VARCHAR(255) COMMENT '个人签名',
    `address` VARCHAR(255) COMMENT '地址',
    `birth` INT(10) COMMENT '生日',
    `gender` CHAR(6) COMMENT '性别',
    `head_pic` VARCHAR(1024) COMMENT '头像',
    `message_date` CHAR(16) DEFAULT 00000000 COMMENT '消息日期',
    `card_id` VARCHAR(255) COMMENT '卡号',
    `email` VARCHAR(255) COMMENT '邮箱地址',
    `current_community_id` INT(10) NOT NULL DEFAULT 0 COMMENT 'community.community_id',
    `latitudeUser` VARCHAR(255) COMMENT '纬度',
    `longitudeUser` VARCHAR(255) COMMENT '经度',
    `w_province` VARCHAR(255) COMMENT '关注所在省/市',
    `w_city` VARCHAR(255) COMMENT '关注所在市/区',
    `register_time` DATETIME COMMENT '注册时间',
    `identify_time` DATETIME COMMENT '认证时间',
    `last_access` DATETIME COMMENT '上次访问时间',
    `is_quit` TINYINT(1) DEFAULT 0 COMMENT '是否退出',
    `user_level` CHAR(32) NOT NULL DEFAULT 'level_0' COMMENT '用户等级',
    PRIMARY KEY (`wx_user_id`),
    UNIQUE KEY `uk_wx_user_vip_no` (`mp_user_id`,`vip_no`),
    KEY `ak_wx_user_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='普通微信用户';